microsoft/playwright-python

- .github/workflows/ci.yml
- .gitignore
- README.md
- build_driver.py
- build_package.py
- playwright_web/playwright.py
- upload_package.py
- added GitHub Action which builds the driver and package on all major operating systems and runs the tests too. Found there the Windows bug, which lead to the behaviour that the `npm` executable could not be found.
- Moved python3 over to python, because mostly either virtualenv, Pipenv or conda will be used
Seems like GitHub Actions needs to be enabled on that repository. Successfully tested on my fork: https://github.com/mxschmitt/playwright-python/actions/runs/160301567
> ci: added initial GitHub Actions

- .github/workflows/ci.yml
- README.md
- local-requirements.txt
- setup.py
- test/conftest.py
- test/test_click.py
As discussed a small showcase how tests with pytest will look like. They are simpler and its easier to have reusable content with pre and post methods called fixtures. In general its more common to use asserts instead of the expect way like we did in JavaScript. For parallelism there are packages out there like [that](https://github.com/pytest-dev/pytest-xdist).
> tests: use pytest instead of unittest

- .gitignore
- README.md
- local-requirements.txt
- playwright_web/browser_context.py
- playwright_web/connection.py
- playwright_web/download.py
- playwright_web/element_handle.py
- playwright_web/file_chooser.py
- playwright_web/frame.py
- playwright_web/helper.py
- playwright_web/js_handle.py
- playwright_web/network.py
- playwright_web/page.py
- playwright_web/transport.py
- setup.py
Fixes #3
Changes:
- added these `if TYPE_CHECKING` conditions to fix circular imports and by that types which were not resolved
- added mypy to the local dependencies and readme to check for typing issues. Currently we have quite a lot of errors (around 40) would be nice to fix them and enforce it in the end on the CI
Tested on Python 3.7.7 and 3.8.2, works. Should I add 3.7 also to our testing matrix in the CI?
> enh: fixed some Python types and Dicts

- .pre-commit-config.yaml
- docs/development.md
- local-requirements.txt
So in general you then can code whatever you want and before you commit it will fix the formatting automatically.
> chore: add black as a pre-commit hook

- .github/workflows/ci.yml
- client.py
- playwright/browser.py
- playwright/browser_context.py
- playwright/connection.py
- playwright/console_message.py
- playwright/element_handle.py
- playwright/file_chooser.py
- playwright/frame.py
- playwright/helper.py
- playwright/js_handle.py
- playwright/main.py
- playwright/network.py
- playwright/page.py
- playwright/transport.py
- setup.cfg
- tests/test_console.py
drive-by: enforced typings on public facing API (playwright dir) and added pragmas to not useful if conditions for coverage reporting.
> devops: separated linting into own job

- playwright/frame.py
`Page.querySelectorAll` called `Frame.querySelectorAll` which was not existing. Tests will follow in the future.
> fix: added querySelectorAll to Frame

- .github/workflows/ci.yml
- .gitignore
- README.md
- setup.cfg
Is the `junit_family=xunit2` change for you okay? Will suppress the warning, that the format will change in pytest 6.0. 
See an example coveralls result page here which is actually already from this PR: https://coveralls.io/jobs/65053338
In further PRs (if merged) it should also be persistent as a Status check down below with the +/- percentage.
> devops: added coveralls as coverage provider

- README.md
- playwright/browser_context.py
- playwright/connection.py
- playwright/page.py
- playwright/sync_base.py
- playwright/wait_helper.py
- tests/assets/historyapi.html
- tests/assets/self-request.html
- tests/test_browsercontext.py
- tests/test_click.py
- tests/test_download.py
- tests/test_element_handle.py
- tests/test_input.py
- tests/test_interception.py
- tests/test_launcher.py
- tests/test_navigation.py
- tests/test_network.py
- tests/test_page.py
- tests/test_popup.py
- tests/test_worker.py
drive-by replacing `asyncio.ensure_future` since "create_task() function is the preferred way for creating new Tasks."
> test: add test_navigation.py (part 1)

- client.py
- playwright/browser_context.py
- playwright/event_context_manager.py
- playwright/file_chooser.py
- playwright/page.py
- playwright/sync.py
- playwright/sync_base.py
- scripts/generate_sync_api.py
- tests/test_browsercontext.py
- tests/test_page.py
As a driver-by, this introduces async context managers that are 100% aligned with the sync ones.
> feat(expect): add typed expectations into the page & browser context.

- playwright/browser.py
- playwright/browser_context.py
- playwright/connection.py
- playwright/element_handle.py
- playwright/frame.py
- playwright/helper.py
- playwright/js_handle.py
- playwright/network.py
- playwright/page.py
Thought about replacing `dict(foo=foo)` with `{"foo": foo}` too but keeping that seems cleaner.
> cleanup: use [] and {} instead classes

- playwright/async_api.py
- playwright/browser_context.py
- playwright/dialog.py
- playwright/js_handle.py
- playwright/network.py
- playwright/sync_api.py
- scripts/documentation_provider.py
- scripts/generate_async_api.py
- scripts/generate_sync_api.py
- tests/test_scripts_documentation_provider.py
Validated and fixed some of the errors. Below is the list of outstanding issues. I did not verify types yet.
```
Not implemented parameter Frame.dblclick(noWaitAfter=)
Not documented parameters: Selectors.register(dict_keys(['path']))
Not documented parameters: Page.waitForRequest(dict_keys(['predicate']))
Not documented parameters: Page.waitForResponse(dict_keys(['predicate']))
Not implemented parameter Page.waitForEvent(optionsOrPredicate=)
Not documented parameters: Page.waitForEvent(dict_keys(['predicate', 'timeout']))
Not implemented parameter Page.setViewportSize(viewportSize=)
Not documented parameters: Page.setViewportSize(dict_keys(['width', 'height']))
Not implemented parameter Page.addInitScript(arg=)
Not documented parameters: Page.addInitScript(dict_keys(['path']))
Not …
```
> feat(docs): validate doc parameters, report errors

- playwright/main.py
- tests/test_sync.py
Previously it was throwing `This event loop is already running`
> fix: multiple Playwright instances

- scripts/documentation_provider.py
Should I make a helper function for `Path(os.path.dirname(os.path.abspath(__file__)))` which accepts `__file__`? We use this quite often in the project.
> chore(docs): use bundled api.md for docs generation

- .github/workflows/ci.yml
- buildbots/test-sync-generation.sh
- playwright/transport.py
- tests/test_generation.py
Mainly because we then know if all the code is used and working
> chore: added tests for generation scripts

- build_driver.py
- build_package.py
- playwright/async_api.py
- playwright/element_handle.py
- playwright/frame.py
- playwright/main.py
- playwright/path_utils.py
- playwright/sync_api.py
- scripts/documentation_provider.py
- scripts/generate_api.py
- tests/conftest.py
- tests/server.py
- tests/test_add_init_script.py
- tests/test_input.py
- tests/test_launcher.py
- tests/test_navigation.py
- tests/test_network.py
- tests/test_page.py
- tests/test_pdf.py
- tests/test_queryselector.py
Drive-by standardise the usage of path objects in the project and cleaned up the tests for the `__dirname` usage.
Lesson learned: if `path` is a string just wrap it in `Path()` as usual. It does also work if `path` is already a `Path` object.
https://docs.python.org/3/library/pathlib.html
> feat: accept pathlib in the API

- playwright/async_api.py
- playwright/event_context_manager.py
- playwright/network.py
- playwright/page.py
- playwright/sync_api.py
- playwright/transport.py
- scripts/generate_api.py
- scripts/generate_async_api.py
- scripts/generate_sync_api.py
- tests/server.py
> By default, Python uses utf-8 encoding.
Fixed also in the web server the unclosed file handlers.
> chore: minor cleanup for coverage

- playwright/sync_api.py
- scripts/generate_sync_api.py
- tests/test_sync.py
> fix: setDefaultTimeout

- .github/workflows/ci.yml
- MANIFEST.in
- build_driver.py
- build_package.py
- buildbots/assets/stub.py
- buildbots/test-package-installations.sh
- driver/main.js
- playwright/main.py
Closes #117
Before:
```
(env) ➜  playwright-python git:(devops/publish-os-specific) du -sh dist/*
89M    dist/playwright-0.0.4.post9+g875b380-py3-none-any.whl
81M    dist/playwright-0.0.4.post9+g875b380.tar.gz
```
After:
```
(env) ➜  playwright-python git:(devops/publish-os-specific) ✗ du -sh dist/*          
24M    dist/playwright-0.0.4.post9+g875b380.d20200801-py3-none-macosx_10_13_x86_64.whl
26M    dist/playwright-0.0.4.post9+g875b380.d20200801-py3-none-manylinux1_x86_64.whl
24M    dist/playwright-0.0.4.post9+g875b380.d20200801-py3-none-win_amd64.whl
300K    dist/playwright-0.0.4.post9+g875b380.d20200801.tar.gz
```
PIP will automatically in the end install the correct wheel since all were uploaded to the PyPi registry.
> devops: separate wheels for OS/drivers

- tests/async/test_focus.py
This ports the JS tests nearly 1:1 with the exception of
variables used with `exposeFunction`. In the JS test `focused`
and `blurred` are booleans but in the Python tests they are lists
that get appended to in the lambda since you cannot assign in lambda
as of 3.7.
> tests: add focus tests

- .github/workflows/ci.yml
- local-requirements.txt
By that we should see easier tests which error by terminating them instead of letting them hang forever.
> devops(tests): added timeout on tests on bots

- playwright/async_api.py
- playwright/browser.py
- playwright/cdp_session.py
- playwright/chromium_browser_context.py
- playwright/element_handle.py
- playwright/frame.py
- playwright/js_handle.py
- playwright/object_factory.py
- playwright/page.py
- playwright/selectors.py
- playwright/sync_api.py
- scripts/generate_api.py
- tests/async/test_cdp_session.py
- tests/async/test_queryselector.py
- driver-by: all optional arguments in the API should be `= None`, not `= defaultValue`.
> feat(cdp): expose cdp session

- playwright/async_base.py
- tests/async/test_console.py
- tests/async/test_dialog.py
- tests/async/test_download.py
- tests/async/test_geolocation.py
- tests/async/test_input.py
- tests/async/test_interception.py
- tests/async/test_launcher.py
- tests/async/test_navigation.py
- tests/async/test_network.py
- tests/async/test_pdf.py
- tests/async/test_popup.py
- tests/async/test_queryselector.py
- tests/async/test_worker.py
- tests/sync/test_accessibility.py
- tests/sync/test_add_init_script.py
- tests/sync/test_check.py
- tests/sync/test_console.py
> tests: migrated some async tests over to sync

- README.md
Let me know if I can improve the wording or forgot some important pieces.
Closes #134
> docs: updated for the Pytest usage

- .github/workflows/ci.yml
- playwright/async_api.py
- playwright/browser_context.py
- playwright/browser_type.py
- playwright/sync_api.py
- scripts/update_api.sh
- tests/async/test_headful.py
- tests/server.py
> tests: added headful tests

- playwright/main.py
Fixes #143
For pytest `-s` is needed.
> fix: forward driver stderr to main stderr

- driver/main.js
- driver/package.json
- playwright/drivers/browsers.json
- tests/async/test_navigation.py
https://playwright.slack.com/archives/C0141EZ6ZNH/p1596655835031400
> feat(roll): roll Playwright 1.2.0-next.1596653191842

- playwright/async_api.py
- playwright/network.py
- playwright/sync_api.py
- tests/async/test_interception.py
- tests/async/test_network.py
- tests/server.py
> feat: added Request.postDataBuffer

- playwright/browser_type.py
- tests/async/test_defaultbrowsercontext.py
> tests: added defaultbrowsercontext tests

- .github/workflows/ci.yml
- README.md
Was more bloat comments in the end rather than useful. If we need it we can execute the command locally to get a coverage report.
> core: drop coveralls tool

- playwright/helper.py
Like we do in upstream:
https://github.com/microsoft/playwright/blob/d4c466868b4a82c3be7ebd697698dd9c129af98d/src/errors.ts#L18-L24
Before
```
>>> message = '''Timeout 30000ms exceeded.\n=========================== logs ===========================\n[api] waiting for selector "[data-testid=dnb-table] tbody tr:nth-child(1):not(.ant-table-placeholder)"\n============================================================\nNote: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.'''
>>> 
stack='''TimeoutError: Timeout 30000ms exceeded.\n=========================== logs ===========================\n[api] waiting for selector "[data-testid=dnb-table] tbody tr:nth-child(1):not(.ant-table-placeholder)"\n============================================================\nNote: use …
```
> fix(error): display correct message

- README.md
- playwright/async_api.py
- playwright/main.py
- playwright/playwright.py
- playwright/sync_api.py
> enh: support for usage in a REPL

- scripts/report_downstream_test_diffs.py
- tests/report_downstream_test_diffs.py
Example Run and Output:
```
$ python tests/report_downstream_test_diffs.py --playwright-js-path=../playwright --api=async
MISSING, MISPELLED, OR MISNAMED:
async/test_accessibility.py::test_autocomplete
…
async/test_workers.py::test_should_have_JSHandles_for_console_logs
async/test_workers.py::test_should_report_console_logs
async/test_workers.py::test_should_report_errors
async/test_workers.py::test_should_report_network_activity
async/test_workers.py::test_should_report_network_activity_on_worker_creation
Missing: 1213, Found: 105
```
Relates #138.
> Add downstream test discrepancy reporter

- playwright/async_api.py
- playwright/element_handle.py
- playwright/sync_api.py
- scripts/documentation_provider.py
- scripts/generate_async_api.py
- scripts/generate_sync_api.py
I went through them, let me know if you are okay with that. In my mind there is no need for now to land more methods since they are almost only CR specific.
```
Method not implemented: Download.createReadStream <- PR open
Method not implemented: BrowserContext.serviceWorkers <- CR specific
Method not implemented: BrowserContext.backgroundPages <- CR specific
Method not implemented: Browser.newBrowserCDPSession <- important?
Method not implemented: BrowserType.launchServer <- decided to not land this in RPC clients. By that also the following methods
Method not implemented: BrowserServer.close
Method not implemented: BrowserServer.process
Method not implemented: BrowserServer.kill
Method not implemented: BrowserServer.wsEndpoint
Method not implemented: BrowserContext.newCDPSession <- its …
```
> chore: add missing methods and use a set for it

- README.md
- driver/package.json
- playwright/drivers/browsers.json
- playwright/element_handle.py
- playwright/selectors.py
- tests/async/test_queryselector.py
Current master is broken because the old Chromium revisions on our CDN were deleted.
> feat(roll): roll Playwright 1.4.0

- .github/workflows/deploy-docs.yml
- .gitignore
- use htmldocs instead of docs because it clashes with the existing docs folder
- use //playwright folder inside of the output folder since it was nested inside
> devops: fixed docs deployment

- README.md
Docstrings at all seem to be not very useful for the user in a file. I replaced it with the rendered version which we created.
> docs(readme): reference to rendered API docs

- README.md
Cleaned up docs and used `<details>` to hide async variants of examples.
> docs(readme): update structure

- playwright/connection.py
- playwright/frame.py
- playwright/wait_helper.py
https://github.com/jfhbrook/pyee/blob/fb45395b408285f5a9a5545d867ce6c5804378c9/pyee/__init__.py#L42-L45
> chore: move to EventEmitter due deprecation warning

- setup.py
Alternatives are:
a) allow bumping a minor version
b) allow bumping a patch version
In my opinion using a exact version is the best for now. We can bump them every few months to stay up to date.
> chore: pin dependencies

- playwright/main.py
Fixes https://github.com/microsoft/playwright-python/issues/215
> fix(subprocess): tolerate spaces in paths

- .pre-commit-config.yaml
Isort 5.x includes a pre-commit configuration (see [docs](https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/#migrating-pre-commit)).
The isort mirror is now deprecated (see [README](https://github.com/pre-commit/mirrors-isort/blob/master/README.md))
> devops: Migrate isort pre-commit hook

- MANIFEST.in
This will allow type checkers to collect type information from this package.
See [PEP 561](https://www.python.org/dev/peps/pep-0561/).
> chore: Add py.typed

- .github/workflows/ci.yml
- local-requirements.txt
- setup.py
Blocked by https://github.com/python-pillow/Pillow/issues/4953
The chance that WK or FF is broken on Python 3.9 is not very big. Lets save some bot minutes!
> devops: Run CI jobs also on Python 3.9

- playwright/main.py
(The user tested it on his environment)
Fixes #246
> fix: AttributeError with mocked stderr (fix #246)

- local-requirements.txt
- tests/async/test_defaultbrowsercontext.py
- tests/async/test_headful.py
We all want 🟢 bots.
This test was flaky over the past few months.
> tests: mark test as flaky

- tests/async/test_navigation.py
- tests/server.py
If pages are cached, then Firefox uses back-forward cache aggressively
to serve the history navigations.
Fixes https://github.com/microsoft/playwright/issues/3693
Fixes #279
> chore: fix test server to disable cache

- build_package.py
Fixes #301 
Use urllib instead of curl for downloading zip files.
> fix: Use urllib instead of curl

- MANIFEST.in
- build_package.py
- scripts/update_versions.py
Removed MANIFEST.in as it is no longer required.
> chore: Remove MANIFEST.in

- playwright/main.py
A fix for https://github.com/microsoft/playwright-python/issues/310
Will this make any bots fail? I am running it locally with `-n 4` and things work, is that not xdist?
> fix(stderr): remove the stderr patching hacks

- playwright/async_base.py
- playwright/sync_base.py
- tests/async/test_websocket.py
Fixes https://github.com/microsoft/playwright-python/issues/251
> chore: document eventemitter methods in the API

- README.md
- playwright/sync_api.py
- scripts/generate_sync_api.py
Fixes https://github.com/microsoft/playwright-python/issues/253
> chore: remove expect_dialog context manager from the sync api

- playwright/page.py
- playwright/video.py
- tests/sync/conftest.py
- tests/sync/test_video.py
Fixes https://github.com/microsoft/playwright-python/issues/334
> fix(video): fix the new recordVideo API

- playwright/connection.py
- tests/async/test_browsercontext.py
- tests/async/test_dialog.py
This allows for async callback functions as an argument to `Page.on`. Relevant [pyee documentation](https://pyee.readthedocs.io/en/latest/#pyee.AsyncIOEventEmitter):
>An event emitter class which can run asyncio coroutines in addition to synchronous blocking functions. For example:
> 
>     @ee.on('event')
>     async def async_handler(*args, **kwargs):
>         await returns_a_future()
> 
>On emit, the event emitter will automatically schedule the coroutine using asyncio.ensure_future and the configured event loop (defaults to asyncio.get_event_loop()).
> 
>Unlike the case with the BaseEventEmitter, all exceptions raised by event handlers are automatically emitted on the error event. This is important for asyncio coroutines specifically but is also handled for synchronous functions for …
> ft: allow async callbacks with Page.on calls

- .github/workflows/publish.yml
Fixes
```
-- tagging: playwright.azurecr.io/public/playwright-python:v0.171.0-focal
Error response from daemon: No such image: playwright:localbuild-focal
```
> fix(devops): use correct tag when publishing to dockerhub

- .github/workflows/publish.yml
Fixes
```
-- tagging: playwright.azurecr.io/public/playwright-python:v0.171.0-focal
Error response from daemon: No such image: playwright:localbuild-focal
```
> fix(devops): use correct tag when publishing to dockerhub (release-170 branch)

- playwright/_impl/_transport.py
We don't need the strict null check since we catch attribute errors. They do it on Pytest side, that seems like established and working for a large user base, so lets use their same implementation as we had before: https://github.com/pytest-dev/pytest/blob/da01ee0a4bb0af780167ecd228ab3ad249511302/src/_pytest/faulthandler.py#L69-L77
fixes #399
fixes #400
> chore(stderr): fix handling without stderr fileno

- playwright/__main__.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/_impl/_transport.py
- tests/async/test_har.py
- tests/async/test_headful.py
- tests/async/test_page.py
Should also be applied to Java, C#, and [Go](https://github.com/mxschmitt/playwright-go/pull/71) but for them its probably not that a high chance that a VSCode user will this kind of special terminal (debug terminal). I used it unintentionally a few months ago if you remember, so makes probably sense to fix it in all the language providers.
Unfortunately we can't fix it on the driver side afaik.
Contains also some other smaller drive-by nits.
> fix(driver): crash with VSCode debug terminal

- .github/workflows/publish_canary_docker.yml
This patch attempts to publish playwright under `playwright/python` mcr
namespace, thus re-using the default `playwrigh` namespace that was
already approved.
Just to be on the safe side, this disables all image publishing except
the one marked with a unique SHA.
> devops: try to publish under playwright namespace in MCR

- .github/workflows/publish_canary_docker.yml
This reverts commit 1f2fcd9353a4f0db0f27b4499d764c932e3ddf49. The old
approach was actually correct.
> Revert "devops: try to publish under playwright namespace in MCR (#445)"

- playwright/_impl/_impl_to_api_mapping.py
- setup.py
- tests/async/test_network.py
Fixes https://github.com/microsoft/playwright-python/issues/538
> fix: don't set attr on bound method

- playwright/_impl/_browser_context.py
- playwright/_impl/_page.py
- tests/async/test_add_init_script.py
- tests/sync/test_add_init_script.py
Fixes https://github.com/microsoft/playwright-python/issues/534
> chore: source -> script in add_init_script messages

- playwright/_impl/_browser_type.py
- playwright/_impl/_helper.py
- tests/async/test_launcher.py
Addresses #477
Fixes #577
and on [Slack](https://playwright.slack.com/archives/C0182HLNSJV/p1615886948000700?thread_ts=1615818192.075500&cid=C0182HLNSJV)
> fix: enhance executable not found check

- playwright/_impl/_transport.py
fixes #571
when using the `async_playwright()` context manager early in an `asyncio.run` program, the `proc` can be garbage collected after the loop is closed. When `proc` is garbage collected the underlying transport is then garbage collected, which tries to kill the running process but cannot without a running loop
> wait for the process

- .github/workflows/ci.yml
- .github/workflows/publish.yml
As done in https://github.com/microsoft/playwright/pull/5787
> chore: install browsers deps using cli

- playwright/_impl/_browser_type.py
- playwright/_impl/_helper.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
> chore: better type annotation for channels

- playwright/_impl/_browser_type.py
[The Nodejs code expects the env param to be of type EnvArr](https://github.com/microsoft/playwright/blob/da1dafcadb05fd648f13610d8eefc4baa5c2261e/src/server/browserType.ts#L139), which is defined as [EnvArray = { name: string, value: string }[];](https://github.com/microsoft/playwright/blob/da1dafcadb05fd648f13610d8eefc4baa5c2261e/src/server/types.ts#L253)
This updates the playwright-python code to format the env dict to the same format to fix the error:
`playwright._impl._api_types.Error: env: expected array, got object`
Example to reproduce error:
```
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
env = {"SSLKEYLOGFILE": "~/test"}
browser = p.chromium.launch(env=env)
page = browser.new_page()
page.goto("http://playwright.dev")
print(page.title()) …
```
> fix: env param in BrowserType.launch doesn't serialize properly to Nodejs

- playwright/_impl/_page.py
- tests/async/test_interception.py
- tests/async/test_video.py
- tests/sync/test_video.py
After enabling the video test again WK+FF failed. The reason for that was a race between `context.on("page")` which comes after `page.on("video")` in WK and FF. This resulted in that the options were not yet there since the `page`->`browserContext` association was not yet there.
Seems like the condition which was removed was a leftover from the old video channels. In upstream PW we don't have such a logic, so lets keep it in sync.
Fixes #608
> test: re-renable CORS tests

- playwright/_impl/_connection.py
- tests/async/test_issues.py
Was hanging before
Closes #536
> fix(connection): handle canceled tasks correctly

- .github/workflows/publish.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- pyproject.toml
- setup.py
Before when building from source using Github ex: 
```console
pip install git+https://github.com/microsoft/playwright-python
```
It failed because multiple wheels were created, hence it failed.
Now there is a special `--all`  flag without which only the wheel for that specific platform would be created hence pip would now work just fine.
Now for uploading to PyPI, `--all` flag would be used to create all the wheels and hence pip install works as expected by the end user. The necessary GitHub actions files are updated for the same for releasing and uploading to PyPI. When user install from GitHub only the driver for that platform is downloaded and hence saves network bandwidth.
Maintainers can try out the new build process with:
```console
pip install …
```
> fix: Installation from source using GitHub

- .pre-commit-config.yaml
- README.md
- local-requirements.txt
- playwright/_impl/_helper.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/expected_api_mismatch.txt
- setup.py
- tests/async/test_navigation.py
- tests/async/test_page.py
https://github.com/microsoft/playwright/commit/653d483ba87190a9fa727fe71c40be202ce9132f
> feat: firefox-stable channel

- setup.py
- tests/test_installation.py
With [PEP 600](https://github.com/mayeut/pep600_compliance/blob/master/DETAILS.rst) this PR restricts installation to Ubuntu 18.04 or higher.
> fix: restrict installation to Ubuntu 18.04

- playwright/_impl/_browser_context.py
- playwright/_impl/_page.py
Fixes #681
not sure about a test for it.
A Set in JavaScript simply does not throw when there is no element which gets removed.
it throws here: https://github.com/microsoft/playwright-python/blob/9d796623a104e082f57878d29d9aea20009b88c1/playwright/_impl/_page.py#L274
> fix: exception when page got closed via browser in persistent context

- README.md
- playwright/_impl/_browser.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_download.py
- playwright/_impl/_helper.py
- playwright/_impl/_page.py
- playwright/_impl/_tracing.py
- playwright/_impl/_transport.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/generate_api.py
- setup.py
- tests/async/test_browsertype_connect.py
- tests/async/test_chromium_tracing.py
- tests/async/test_download.py
- tests/async/test_tracing.py
- tests/sync/test_browsertype_connect.py
Roll Playwright driver to 1.12.0-next-1620880294000
> feat(roll): roll to Playwright 1.12.0-next-1621456974000

- tests/async/test_page.py
- tests/async/test_tracing.py
- tests/async/test_websocket.py
Mark https://github.com/microsoft/playwright/issues/6725 as flaky and skip the tracing test, since its broken upstream currently. We will add more tests / fix it once we release v1.12
> tests: fix flaky tests iteration 2

- playwright/_impl/_file_chooser.py
Backports from upstream: https://github.com/microsoft/playwright/pull/6647
> fix: compute payload mime type on server

- tests/conftest.py
There is no special handling required for windows so the code was redundant and hence removed.
> chore: Kill windows subprocess using kill

- playwright/_impl/_transport.py
I use playwright python in silent mode, my app runs in a background with no windows.
The Windows platform has a special way to run such applications - pythonw.exe
When I start the browser from my code, an unwanted black console window appears on the screen.
How to reproduce the problem:
Let's take simple script like this:
```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
browser = p.chromium.launch()
page = browser.new_page()
page.goto("http://playwright.dev")
page.screenshot(path="example.png")
print(page.title())
browser.close()
```
If we run this script like this:
`python.exe sample.py`
Everything will work fine and no windows will appear
If we run it like this
`pythonw.exe sample.py`
We will see a black console window associated with the call to …
> Fix unwanted console window with pythonw on windows platform

- playwright/_impl/_network.py
- tests/async/test_websocket.py
Its not 1:1 the same as upstream:
https://github.com/microsoft/playwright/blob/409aeaa4438585f44484bfc9d43e7d51f9b5c22a/tests/web-socket.spec.ts#L52-L73
> test: unflake test_should_emit_frame_events test

- playwright/__main__.py
Bug: When the installation was failing due e.g. a TCP timeout it still reported exit code 0. With this change it now forwards all CLI exit codes to the parent.
> fix(cli): forward CLI exit code over to the parent

- playwright/_impl/__pyinstaller/__init__.py
- playwright/_impl/__pyinstaller/hook-playwright.async_api.py
- playwright/_impl/__pyinstaller/hook-playwright.sync_api.py
- playwright/_impl/_transport.py
- setup.py
For review instructions:
- Create a file `main.py`
- add this to the file 
```python
import os
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
browser = p.chromium.launch()
page = browser.new_page()
page.goto("http://whatsmyuseragent.org/")
page.screenshot(path="example.png")
browser.close()
```
- If you want to bundle browsers then set `PLAYWRIGHT_BROWSERS_PATH=0` to include bowser's inside the binary and then download the browsers 
- installer pyinstaller 
```sh
pip install pyinstaller
```
- Run pyinstaller on the file like 
```sh
pyinstaller -F main.py
```
- Binary would be placed in `dist/` relative to current dir and test it
> feat: added hooks for pyinstaller

- .github/workflows/ci.yml
- playwright/_impl/_connection.py
- playwright/_impl/_frame.py
- playwright/_impl/_wait_helper.py
- tests/assets/networkidle.html
- tests/assets/networkidle.js
- tests/async/test_accessibility.py
- tests/async/test_navigation.py
- tests/sync/test_accessibility.py
> fix: migrate to new waitForEventInfo handling

- playwright/_impl/_transport.py
Earlier mypy was broken for the websockets library, this PR fixes it as per the recommended import https://websockets.readthedocs.io/en/stable/changelog.html#id5
> fix: fix websockets for mypy 

- playwright/_impl/_browser_type.py
When the OS dependencies are not satisfied, Playwright throws an exception with `npx playwright install-deps`. This will also trigger this if condition, but it should not. To prevent that for the release we add a space after it.
For 1.15 this logic is not relevant anymore, since we don't wrap it in Python anymore. We throw it from Node.js directly in the correct format.
> fix(1.14): do not trigger playwright install message for deps

- .github/workflows/ci.yml
- local-requirements.txt
- setup.py
Python 3.10rc is out and hence we should add it to CI to prevent breakage when the final is out.
> chore: test on python 3.10

- playwright/_impl/_playwright.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/generate_async_api.py
- scripts/generate_sync_api.py
- tests/common/test_threads.py
Cleans up special handling for `__getitem__` as there is now a list of allowed methods without docs and makes it more maintainable as more dunder methods would be added.
> chore: remove special handling for `__getitem__`

- playwright/_impl/_async_base.py
- playwright/_impl/_sync_base.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/documentation_provider.py
- scripts/generate_api.py
- scripts/generate_async_api.py
- scripts/generate_sync_api.py
- setup.cfg
Closes https://github.com/microsoft/playwright-python/issues/786
> chore: generate events docs

- README.md
- playwright/_impl/_async_base.py
- playwright/_impl/_helper.py
- playwright/_impl/_locator.py
- playwright/_impl/_sync_base.py
- playwright/_impl/_transport.py
- playwright/async_api/__init__.py
- playwright/async_api/_generated.py
- playwright/sync_api/__init__.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_locators.py
- Roll to 1.16.0-next-1632960932000
- Some typing fixes
> chore: roll to 1.16.0-next-1632960932000

- tests/async/test_tracing.py
- tests/sync/test_tracing.py
> test: add tracing related tests

- playwright/_impl/_locator.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_locators.py
- tests/sync/test_locators.py
> feat(roll): roll Playwright 1.18.0-next-1636539685000

- setup.py
Since Nov 16, 2021, we have the following conventions:
- Drivers published from tip-of-tree have an `-alpha` version and are
stored at `/next` subfolder on Azure Storage.
- Drivers auto-published for each commit of the release branch have a `-beta` version and are
stored at `/next` subfolder on Azure Storage.
- Drivers published due to a release might have `-rc` as part of the
version, and are stored in root subfolder on Azure Storage.
We no longer have driver versions that include "next" as part of the
version. I kept it for backwards compatibility.
> chore: smart detection for a driver download url

- setup.py
Before this CL if you have used setup.py -all it resulted in that the local driver got overridden by the last matching downloaded driver. Only Linux or MacOS this would be then the wrong architecture in most cases.
drive-by: had to rename it a bit, because it conflicted otherwise with the imported platform module.
> fix: setup.py --all only put local driver if arch matches

- README.md
- playwright/_impl/_assertions.py
- playwright/_impl/_browser.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_fetch.py
- playwright/_impl/_frame.py
- playwright/_impl/_local_utils.py
- playwright/_impl/_locator.py
- playwright/_impl/_network.py
- playwright/_impl/_object_factory.py
- playwright/_impl/_page.py
- playwright/_impl/_playwright.py
- playwright/_impl/_str_utils.py
- playwright/_impl/_tracing.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_assertions.py
- tests/async/test_download.py
- tests/async/test_fetch_global.py
- tests/async/test_locators.py
- tests/async/test_page.py
- tests/async/test_tracing.py
- tests/sync/test_assertions.py
- tests/sync/test_locators.py
- tests/sync/test_tracing.py
> chore: roll Playwright to 1.18.0-beta-1642508722000

- playwright/_impl/_network.py
Fixes:
```
/Users/max/development/playwright-python/playwright/_impl/_network.py:270: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
await asyncio.wait(
```
> chore: fix deprecation warning

- README.md
- playwright/_impl/_assertions.py
- playwright/_impl/_browser.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_fetch.py
- playwright/_impl/_object_factory.py
- playwright/_impl/_tracing.py
- playwright/async_api/__init__.py
- playwright/async_api/_generated.py
- playwright/sync_api/__init__.py
- playwright/sync_api/_generated.py
- scripts/generate_api.py
- scripts/generate_async_api.py
- scripts/generate_sync_api.py
- setup.py
- tests/assets/error.html
- tests/async/test_assertions.py
- tests/async/test_browsercontext_add_cookies.py
- tests/async/test_browsercontext_cookies.py
- tests/async/test_defaultbrowsercontext.py
- tests/async/test_headful.py
- tests/async/test_resource_timing.py
- tests/sync/test_assertions.py
Fixes https://github.com/microsoft/playwright-python/issues/1104
Backports https://github.com/microsoft/playwright/pull/10954/files
> feat: add Response assertions

- playwright/_impl/_transport.py
Proposed fix for issue #1148.
When playwright is running in an application which was packaged by pyinstaller, `stderr` can be of type `NullWriter` which has no attribute `closed`.  Moved access to the attribute `closed` inside the following `try` clause to handle the `AttributeError`.
Re-run unit tests after the change an no additional failures seen.
> fix: handle pyinstaller app with no stderr (#1148)

- playwright/_impl/_network.py
> fix: Task exception was never retrieved when continue_ race with page closed event

- playwright/_impl/_sync_base.py
- tests/async/test_assertions.py
- tests/sync/test_assertions.py
This fixes the following failure:
```
================================== FAILURES ===================================
_________________ test_assertions_page_to_have_title[firefox] __________________
page = <Page url='http://localhost:49309/empty.html'>
server = http://localhost:49309
def test_assertions_page_to_have_title(page: Page, server: Server) -> None:
page.goto(server.EMPTY_PAGE)
page.set_content(
"""
<script>
document.title = 'new title';
setTimeout(() => {
document.title = 'great title';
}, 2000);
</script>
"""
)
expect(page).to_have_title("new title")
expect(page).to_have_title(re.compile("new title"))
with pytest.raises(AssertionError):
expect(page).to_have_title("not the current title", timeout=100)
with pytest.raises(AssertionError):
expect(page).to_have_title(re.compile("not …
```
> test: fix flaky assertion tests

- playwright/_impl/_connection.py
- tests/async/test_asyncio.py
Fixes https://github.com/microsoft/playwright-python/issues/1210
Imagine Page.waitForSelector, if a user cancels one of these api calls, the internal protocol calls are still pending and don't get canceled. When one of these errors out it setts the exception and it ends up in `'Future exception was never retrieved'` (asyncio warning). I thought about two ways so far of fixing it:
a) if the outer task gets canceled "propagate" the canceled signal down to the protocol api call, see here for an impl: https://github.com/microsoft/playwright-python/pull/1236/commits/2f8041c0754c96bbff4a23cc10ae2cc4c22ab572
b) store the "outer task" inside the ProtocolCallback class and check when receiving the error if it was canceled: https://github.com/microsoft/playwright-python/pull/1236/files
Not sure …
> fix: forward cancelled tasks to the inner task

- .github/workflows/test_docker.yml
- utils/docker/Dockerfile.bionic
- utils/docker/Dockerfile.focal
This will enhance error reporting
> chore: mark docker images as Playwright

- .github/workflows/test_docker.yml
`/root/playwright` inside the Docker container is owned by `1001:121` (`runner:docker`) which is != `root:root` thats why we get the following error message:
```
root@4d691546890c:~/playwright# git log
fatal: unsafe repository ('/root/playwright' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /root/playwright
```
The folder was created by the checkout action from GitHub Actions, which uses the GitHub Action default user for that.
Relates to https://github.com/git/git/commit/8959555cee7ec045958f9b6dd62e541affb7e7d9
cc/FYI @dscho
> test: fix Docker tests

- playwright/_impl/_frame.py
- playwright/_impl/_locator.py
- playwright/_impl/_page.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_locators.py
- tests/async/test_queryselector.py
Partial revert of ed13a53281bc213e1a4341c50d47fbc65670288f
Ports the following changes:
Resolves #1299
> chore: remove layout locators, roll to 1.22.0

- playwright/_impl/_playwright.py
- playwright/_impl/_selectors.py
- tests/sync/conftest.py
- tests/sync/test_queryselector.py
- pass Playwright dispatching fiber down to the Selector class instance
- port https://github.com/microsoft/playwright-python/blob/97c64908216aec0afe9d6a9a0277fecebc3b2ae3/tests/async/test_queryselector.py to the sync variant
Fixes https://github.com/microsoft/playwright-python/issues/1324
> fix: sync selectors

- tests/async/test_interception.py
- tests/async/test_websocket.py
We only run the tests on macOS 11+, so I don't keep the check for making them pass on macos10.15.
This fixes:
- test_page_route_should_be_abortable_with_custom_error_codes[webkit]
- test_page_route_should_fail_navigation_when_aborting_main_resource[webkit]
> test: fix WebKit tests

- tests/async/test_browsertype_connect.py
The guess is that the webserver takes longer to process and then the click times out.
> test: unflake test_should_upload_large_file

- .github/workflows/ci.yml
- tests/test_reference_count_async.py
> devops: only install required OS dependencies

- README.md
- playwright/_impl/_api_structures.py
- playwright/_impl/_assertions.py
- playwright/_impl/_browser.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_frame.py
- playwright/_impl/_helper.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/expected_api_mismatch.txt
- setup.py
- tests/async/test_assertions.py
- tests/async/test_browser.py
- tests/async/test_browsercontext_service_worker_policy.py
- tests/async/test_defaultbrowsercontext.py
- tests/async/test_har.py
- tests/async/test_network.py
- tests/async/test_page.py
- tests/sync/test_assertions.py
- tests/sync/test_browser.py
- tests/sync/test_browsercontext_service_worker_policy.py
- tests/sync/test_har.py
- tests/sync/test_network.py
This is part 1/n of the 1.23 port.
Relates #1308.
Ports:
> chore(roll): roll Playwright to 1.23.0-beta-1656026605000

- playwright/_impl/_browser.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_connection.py
- playwright/_impl/_fetch.py
- playwright/_impl/_object_factory.py
- playwright/_impl/_tracing.py
This is part 4/n of the 1.23 port.
Relates #1308, #1374, #1376, #1382
Ports:
> chore: expose local_utils

- playwright/_impl/_browser.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_helper.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/expected_api_mismatch.txt
- setup.py
- tests/async/test_har.py
- tests/async/test_request_intercept.py
- tests/server.py
- tests/sync/test_har.py
- tests/sync/test_request_intercept.py
This is part 3/n of the 1.23 port.
Relates #1308, #1374, #1376.
Ports:
> chore: port record_har_* options (content, mode, url_filter)

- playwright/_impl/_browser_context.py
- playwright/_impl/_helper.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/expected_api_mismatch.txt
- tests/assets/global-var.html
- tests/async/test_browsercontext_request_fallback.py
- tests/async/test_browsercontext_request_intercept.py
- tests/async/test_page_request_fallback.py
- tests/sync/test_browsercontext_request_fallback.py
- tests/sync/test_browsercontext_request_intercept.py
- tests/sync/test_page_request_fallback.py
This is part 2/n of the 1.23 port.
Relates #1308, #1374
Ports:
> chore: port route chaining, fallback, async, times

- playwright/_impl/_frame.py
- tests/sync/test_page.py
Fixes #1399.
Ports in #1374 of https://github.com/microsoft/playwright/commit/cdb862767f408fa6d364179d449f562565b4a793
was incorrect.
> fix: emit Page on load/DOMContentLoaded

- playwright/_impl/_frame.py
- tests/sync/test_page.py
Fixes #1399.
Ports in #1374 of https://github.com/microsoft/playwright/commit/cdb862767f408fa6d364179d449f562565b4a793
was incorrect.
> cherry-pick(#1400): fix: emit Page on load/DOMContentLoaded

- playwright/_impl/_connection.py
- playwright/_impl/_network.py
- playwright/_impl/_wait_helper.py
- tests/async/test_tracing.py
- tests/sync/test_tracing.py
Fixes https://github.com/microsoft/playwright-python/issues/1397
> fix(tracing): apiName calculation for route handlers

- playwright/_impl/_browser_type.py
> fix: support empty string as persistent context path

- playwright/_impl/_browser_context.py
- playwright/_impl/_helper.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- tests/async/test_browsercontext_request_intercept.py
- tests/async/test_har.py
- tests/async/test_request_intercept.py
- tests/sync/test_browsercontext_request_intercept.py
- tests/sync/test_har.py
- tests/sync/test_request_intercept.py
This reverts commit c8d8f4a6859ac210fa6b6f01eb636fc11065abb9.
* It's not exhaustive, and running the originally reported sample on 1.22 also yields errors.
* There are many other places where we do `asyncio.create_task`  without awaiting from before async handlers where added, and they need to be dealt with too.
* We likely want to either loop over all tasks in the loop (assuming we created the loop) and kill them when we exit PW ContextManager, (2) more exhaustively track the background tasks (i.e. do what we do in this patch, but wrap some more create_async callsites), or (3) something else!
Relates 1402.
> Revert "fix: cleanup pending route handlers on close (#1412)"

- playwright/sync_api/_context_manager.py
Fixes https://github.com/microsoft/playwright-python/issues/1402
> fix(tasks): cancel all the pending tasks as we exit own loop

- README.md
- playwright/_impl/_js_handle.py
- playwright/_impl/_locator.py
- playwright/_impl/_network.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_evaluate.py
- tests/async/test_locators.py
> chore: roll Playwright to 1.24.0-beta-1657919681000

- playwright/_impl/_assertions.py
- playwright/_impl/_browser.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_frame.py
- playwright/_impl/_helper.py
- playwright/_impl/_locator.py
- playwright/_impl/_page.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/documentation_provider.py
Fixes #1415.
Most of this change was generated. The actual changed code (aside from find and replace) is in `//scripts/documentation_provider.py`.
NB: Using bytes in patterns with our code will currently explode, so
this constrains to hint to users to use str patterns:
```py
await expect(page).to_have_url(re.compile(r".*/grid\.html"))
await expect(page).to_have_url(re.compile(rb".*/grid\.html"))
```
This change opts to constrain the type rather than allow for bytes, too. If a user wants to use bytes, they can encode/decode explicitly.
> chore: constrain Pattern type

- playwright/_impl/_locator.py
- playwright/_impl/_str_utils.py
- tests/async/test_locators.py
- tests/sync/test_locators.py
Fixes https://github.com/microsoft/playwright-python/issues/1434
> fix: do not encode unicodes with locator has/has_text

- playwright/_impl/_network.py
> fix Route.abort not report handled

- README.md
- playwright/_impl/_browser_context.py
- playwright/_impl/_connection.py
- setup.py
- tests/async/test_launcher.py
- Roll to fix MSEdge downloads
Ports:
- [chore: reparent context objects into the object (#15689)](https://github.com/microsoft/playwright/commit/a198b6d753d7710be55236ea31256c9518fb9cf5)
Resolves #1398.
> chore: roll Playwright to 1.25.0-alpha-jul-26-2022

- playwright/_impl/_network.py
> cherry-pick(#1458): fix: route.abort failed missing handle report

- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/generate_api.py
Resolves #1460.
This ensures the generated code does not use implicit optional. We can do another follow up if we don't want the implicit optionals in our internal code, but that is not planned at this time.
> chore: fix implicit optional

- .github/workflows/test_docker.yml
- .github/workflows/trigger_internal_tests.yml
- utils/docker/Dockerfile.jammy
- utils/docker/build.sh
- utils/docker/publish_docker.sh
Resolves https://github.com/microsoft/playwright-python/issues/1294.
For now, we leave `focal` as the default docker image. When v1.25 is announced, we can notify users the default base image will be changing in some future release (v1.26?) to jammy. (We should coordinate this across language ports.)
As of this writing, Python 3.10 is what ships in our jammy image.
Testing:
- Until jammy is our default base image, we'll run our tests in both focal and jammy in CI.
- This repo's tests covers amd; internal bots will cover arm.
> chore: publish official jammy image

- .pre-commit-config.yaml
- playwright/_impl/_sync_base.py
Hi, small patch to bump pre-commit hook versions and silence the current `mypy` complaints about the sync api base.
Thanks
> `pre-commit` version upgrades

- playwright/_impl/_assertions.py
- playwright/_impl/_helper.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_assertions.py
- tests/sync/test_assertions.py
> chore: roll Playwright to 1.25.0

- playwright/_impl/_playwright.py
- tests/async/test_device_descriptors.py
Fixes #1496.
Adds tests for documented case, too: https://playwright.dev/python/docs/emulation#devices
> feat: expose default_browser_type in emulated devices

- tests/async/test_device_descriptors.py
Follow-up to #1497.
Fixes https://github.com/microsoft/playwright-python/runs/7843392919?check_suite_focus=true.
> test: ensure device descriptor tests pass on chrome bots

- setup.py
Before it was the following:
```
>>> find_packages(exclude=["tests*"])
['playwright', 'playwright._impl', 'playwright.async_api', 'playwright.sync_api', 'playwright._impl.__pyinstaller']
```
after reducing it to the shown in the PR, it was still fine with my local integration tests (build wheel, install from wheel).
Fixes https://github.com/microsoft/playwright-python/issues/1504.
> chore(build): have allow-list in setup.py included packages

- .github/workflows/ci.yml
- meta.yaml
- scripts/generate_api.py
- scripts/generate_async_api.py
- scripts/generate_sync_api.py
- setup.py
Fixes https://github.com/microsoft/playwright-python/issues/1395
> chore: add support for Python 3.11

- tests/sync/test_locator_get_by.py
Mirrors upstream test. Implementation is already good.
> test: add get_by_text escaping with multiple space sequences

- playwright/_impl/_frame.py
- tests/async/test_wait_for_function.py
Fixes https://github.com/microsoft/playwright-python/issues/1584
> fix: wait_for_function with polling interval

- playwright/_impl/_impl_to_api_mapping.py
- tests/test_reference_count_async.py
fixes https://github.com/microsoft/playwright-python/issues/1602
> chore: fix impl to api name memory leak

- playwright/_impl/_impl_to_api_mapping.py
- playwright/_impl/_js_handle.py
- pyproject.toml
Also verified that https://github.com/microsoft/playwright-python/pull/1604 was reported with this linting rule before.
> chore: don't use a function call in default initializer

- playwright/_impl/_js_handle.py
Based on https://github.com/microsoft/playwright-python/pull/1604#issuecomment-1299676903.
> chore: follow-up to reduce memory footprint

- playwright/_impl/_browser_context.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_connection.py
- playwright/_impl/_js_handle.py
- playwright/_impl/_json_pipe.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/_impl/_playwright.py
- playwright/sync_api/_context_manager.py
Extracted from https://github.com/microsoft/playwright-python/pull/1637.
> chore: various type fixes

- meta.yaml
- playwright/_impl/_connection.py
- playwright/_impl/_json_pipe.py
- setup.py
Fixes https://github.com/microsoft/playwright-python/pull/1587
Gets merged after #1636 has landed.
> chore: bump pyee to 9.0.4

- playwright/_impl/_transport.py
Fixes https://github.com/microsoft/playwright-python/issues/1646
Saw this popping up multiple times in the past from different customers. In .NET we e.g. set this bit also always on Windows: https://github.com/microsoft/playwright-dotnet/blob/main/src/Playwright/Transport/StdIOTransport.cs#L120
> chore: hide Window always on Windows

- playwright/_impl/_frame.py
- playwright/_impl/_locator.py
- playwright/_impl/_page.py
- playwright/_impl/_selectors.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_selector_generator.py
- tests/async/test_selectors_get_by.py
Fixes https://github.com/microsoft/playwright-python/issues/1632
> chore: roll to 1.28.0-beta-1668538774000

- playwright/_impl/_locator.py
The `get_by_role()` locator currently throws an error (`Unknown attribute “include-hiddenen“`) when using the include_hidden attribute (e.g. `page.get_by_role("radio", include_hidden=True)`).
I fixed the typo which leads to this error.
> fix: include-hidden arg in get_by_role_selector

- README.md
- playwright/_impl/_page.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/expected_api_mismatch.txt
- setup.py
1.30 roll except toIntesectViewport since we wait there for upstream API follow-ups.
https://github.com/microsoft/playwright-python/issues/1687
> chore(roll): roll Playwright to 1.30.0-alpha-jan-16-2023

- README.md
- playwright/_impl/_api_structures.py
- playwright/_impl/_assertions.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_helper.py
- playwright/_impl/_locator.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/_impl/_str_utils.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_expect_misc.py
- tests/async/test_navigation.py
- tests/async/test_page.py
- tests/async/test_page_network_response.py
- tests/async/test_page_request_intercept.py
- tests/async/test_resource_timing.py
- tests/async/test_selectors_get_by.py
- tests/server.py
- tests/sync/test_expect_misc.py
- tests/sync/test_page_network_response.py
- tests/sync/test_page_request_fallback.py
- tests/sync/test_request_intercept.py
- tests/sync/test_resource_timing.py
Fixes https://github.com/microsoft/playwright-python/issues/1738
> chore(roll): roll to 1.31.0-beta-1676906983000

- playwright/_impl/_transport.py
Before that the transport used to hang when the process died.
Fixes https://github.com/microsoft/playwright-python/issues/1779
> fix: throw when driver crashes

- tests/async/test_input.py
This mirrors the following upstream logic: https://github.com/microsoft/playwright/blob/3ff3567c89a774a9e2086af07a858266d84d41fe/tests/page/wheel.spec.ts#L25-L34
> test: make wheel tests pass on CR/darwin

- playwright/_impl/_helper.py
- tests/async/test_page.py
- tests/sync/test_sync.py
Fixes https://github.com/microsoft/playwright-python/issues/1883
> fix: inherit context timeout correctly

- playwright/async_api/_context_manager.py
- playwright/sync_api/_context_manager.py
- tests/async/test_asyncio.py
- tests/sync/test_sync.py
Extracted from https://github.com/microsoft/playwright-python/pull/1891.
> chore: allow to call Playwright.stop() multiple times

- playwright/_impl/_sync_base.py
- tests/sync/test_sync.py
Extracted from https://github.com/microsoft/playwright-python/pull/1891.
> chore: print pretty exception after playwright.stop()

- playwright/_impl/_connection.py
Fixes https://github.com/microsoft/playwright-python/issues/1903
Tricky to test that a warning does not get displayed. Before the following:
```python
from playwright.sync_api import sync_playwright
with sync_playwright() as playwright:
browser = playwright.chromium.launch()
page = browser.new_page()
page.goto('http://example.com/')
with page.expect_popup() as popup_info:
page.evaluate('window.open("http://example.com/")')
popup = popup_info.value
with popup.expect_event('close') as popup_info:
popup.evaluate('window.close()')
browser.close()
```
resulted in:
```
(env) ➜  playwright-python git:(main) ✗ python test.py
Future exception was never retrieved
future: <Future finished exception=Error('Target page, context or browser has been closed')>
playwright._impl._api_types.Error: Target …
```
> chore: do not continue with no_reply messages

- playwright/_impl/_browser_type.py
- tests/async/test_browsertype_connect_cdp.py
Fixes https://github.com/microsoft/playwright-python/issues/1910
> fix: make it possible to send connect_over_cdp headers

- utils/docker/Dockerfile.focal
- utils/docker/Dockerfile.jammy
Background: We by accident were installing the temporary snapshot release globally inside the Docker container.
Fix: We instead install Playwright in a virtualenv, so only the deps + browsers are installed like we promise.
-> no global installed Playwright library anymore.
Fixes https://github.com/microsoft/playwright-pytest/issues/169
> chore: don't have Playwright globally installed in Docker image

- README.md
- playwright/_impl/_browser.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_connection.py
- playwright/_impl/_console_message.py
- playwright/_impl/_dialog.py
- playwright/_impl/_locator.py
- playwright/_impl/_page.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_accessibility.py
- tests/async/test_browsercontext_events.py
- tests/async/test_locators.py
- tests/async/test_popup.py
- tests/async/test_selectors_misc.py
- tests/sync/test_accessibility.py
Fixes https://github.com/microsoft/playwright-python/issues/1885
> chore(roll): roll Playwright to 1.34.0-alpha-may-17-2023

- playwright/_impl/_transport.py
- tests/common/test_signals.py
Issue what this solves is that by default if a user presses Command + C it will send it to the `main.py` script (good) but also to the `driver` (bad) which will instantly close the browsers etc. This is because the driver is getting launched as the same process group, we should launch it as a separate process group imo.
See https://unix.stackexchange.com/a/149756
Since upstream we can do the following:
```ts
(async () => {
const browser = await chromium.launch({ handleSIGINT: false, handleSIGHUP: false, handleSIGTERM: false, headless: false });
const context = await browser.newContext();
const page = await context.newPage();
let exited = false;
process.on('SIGINT', async () => {
exited = true;
console.log('SIGINT signal received, graceful shutdown!');
await context.close();
await …
```
> test: add test for Command + C does not terminate driver connection

- README.md
- playwright/_impl/_browser_context.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_browsercontext.py
- tests/async/test_browsercontext_events.py
- tests/async/test_interception.py
- tests/sync/test_browsercontext_events.py
- tests/sync/test_locators.py
- tests/sync/test_selectors_misc.py
Fixes https://github.com/microsoft/playwright-python/issues/1928
> chore(roll): roll Playwright to 1.34.3

- playwright/async_api/__init__.py
- playwright/sync_api/__init__.py
We do a good job in resetting the expect timeout here:
https://github.com/microsoft/playwright-python/blob/d4a874f3eebbb70dfc6f915dc607e27d079cc5fb/tests/async/test_assertions.py#L801-L810
but it gets ignored here, which ends up that the timeout is not getting reset to the default:
https://github.com/microsoft/playwright-python/blob/f1c11fbd3000ee072b117ddebed9da1e0c2226b3/playwright/async_api/__init__.py#L104-L105
So lets check if the param got actually passed over as per [here](https://stackoverflow.com/a/14749388/6512681).
Fixes https://github.com/microsoft/playwright-python/issues/1973
> chore: improve expect.set_options timeout reset handling

- playwright/_impl/_transport.py
This follows what we do in Playwright for .NET here:
https://github.com/microsoft/playwright-dotnet/commit/741de1de35f94c5e209a6d48150e5656dba6acb6
what they do internally here:
https://github.com/dotnet/runtime/blob/31106939ba524a7e6df8225cf8d0fedefba92b9f/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs#L498-L502
I made sure that it does not regress https://github.com/microsoft/playwright-python/issues/1711
Fixes https://github.com/microsoft/playwright-python/issues/1778
TL;DR: The Process creationflag [CREATE_NO_WINDOW](https://learn.microsoft.com/en-us/windows/win32/procthread/process-creation-flags) does not work, but setting the startupinfo manually works.
> chore: hide Batch window on win32

- README.md
- playwright/_impl/_js_handle.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_evaluate.py
Playwright for Python does not have its own glob to regex implementation, we rely on Python stdlib see here:
https://github.com/microsoft/playwright-python/blob/6980e901849b6fd551e53cd5e2d298f60ac8977b/playwright/_impl/_helper.py
Fixes https://github.com/microsoft/playwright-python/issues/1986
> chore(roll): roll Playwright to v1.36.0

- .github/workflows/ci.yml
- .github/workflows/publish.yml
There are two issues which we experience with the latest conda version:
macos:
```
Traceback (most recent call last):
File "/usr/local/miniconda/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
return func(*args, **kwargs)
File "/usr/local/miniconda/lib/python3.10/site-packages/conda/cli/main.py", line 6[9](https://github.com/microsoft/playwright-python/actions/runs/5797448985/job/15713019320#step:5:10), in main_subshell
exit_code = do_call(args, p)
File "/usr/local/miniconda/lib/python3.[10](https://github.com/microsoft/playwright-python/actions/runs/5797448985/job/15713019320#step:5:11)/site-packages/conda/cli/conda_argparse.py", line [11](https://github.com/microsoft/playwright-python/actions/runs/5797448985/job/15713019320#step:5:12)5, in do_call
return …
```
> devops: fix conda build pipeline (pin conda)

- meta.yaml
Conda version identifier should not have a v prefix, we did this by accident.
> devops: do not publish conda packages with v prefix

- README.md
- playwright/_impl/_artifact.py
- playwright/_impl/_browser.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_locator.py
- playwright/_impl/_stream.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_locators.py
- tests/async/test_navigation.py
Fixes https://github.com/microsoft/playwright-python/issues/2014
> chore(roll): roll Playwright to 1.37.0-alpha-aug-8-2023

- playwright/_impl/_transport.py
Fixes https://github.com/microsoft/playwright-python/issues/2034
> fix: allow sys.stderr.fileno() to throw NotImplementedError

- README.md
- playwright/_impl/_browser_context.py
- playwright/_impl/_js_handle.py
- playwright/_impl/_web_error.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/generate_api.py
- setup.py
- tests/async/test_browsercontext_events.py
- tests/async/test_evaluate.py
Fixes https://github.com/microsoft/playwright-python/issues/2061
> chore(roll): roll Playwright to 1.38.0

- README.md
- playwright/_impl/_assertions.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_connection.py
- playwright/_impl/_console_message.py
- playwright/_impl/_js_handle.py
- playwright/_impl/_local_utils.py
- playwright/_impl/_object_factory.py
- playwright/_impl/_playwright.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_evaluate.py
- tests/async/test_keyboard.py
https://github.com/microsoft/playwright-dotnet/issues/2690
> chore: roll Playwright to 1.39.0-alpha-oct-10-2023

- setup.py
This got by accident removed [here](https://github.com/microsoft/playwright-python/commit/9f042eca1ce2f29b662b442d61462b1c5a87fdaf#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L238).
Since we are not (yet) using the [isolated build system](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html), we need to install setuptools_scm from the outside. If we would have used it, it would have picked up the build system dependencies from [here](https://github.com/microsoft/playwright-python/blob/147e4a3a3f6ffa19ad6639cbcc27323fc3163fe9/pyproject.toml#L1-L3).
> chore: restore setup_requires in setup.py

- tests/sync/test_assertions.py
I don't think this case has anything to do with `to_have_js_property`?
> `test_to_have_js_property_assertions_locator_to_have_text` => `test_assertions_locator_to_have_text`

- playwright/_impl/_browser.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_page.py
- playwright/_impl/_tracing.py
- tests/sync/test_assertions.py
Backports missed changes from here https://github.com/microsoft/playwright-python/issues/2061.
Fixes https://github.com/microsoft/playwright-python/issues/2137
> fix: relative Firefox record_video_dir

- playwright/_impl/_browser_context.py
- tests/async/test_page.py
- tests/conftest.py
- tests/sync/test_page.py
Fixes https://github.com/microsoft/playwright-python/issues/2154
> fix: page.pause() timeout reset

- README.md
- playwright/_impl/_assertions.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_element_handle.py
- playwright/_impl/_frame.py
- playwright/_impl/_set_input_files_helpers.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/assets/file-to-upload-2.txt
- tests/async/test_assertions.py
- tests/async/test_browsertype_connect.py
- tests/async/test_evaluate.py
- tests/async/test_input.py
- tests/sync/test_assertions.py
- tests/sync/test_browsertype_connect.py
- tests/sync/test_input.py
Fixes https://github.com/microsoft/playwright-python/issues/2078
> chore(roll): roll Playwright to 1.40.0

- playwright/_impl/_api_structures.py
- playwright/_impl/_assertions.py
- playwright/_impl/_browser.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_connection.py
- playwright/_impl/_element_handle.py
- playwright/_impl/_file_chooser.py
- playwright/_impl/_frame.py
- playwright/_impl/_impl_to_api_mapping.py
- playwright/_impl/_js_handle.py
- playwright/_impl/_locator.py
- playwright/_impl/_page.py
- playwright/_impl/_set_input_files_helpers.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- pyproject.toml
- scripts/documentation_provider.py
- scripts/generate_api.py
- tests/async/test_browsercontext_request_fallback.py
- tests/async/test_interception.py
- tests/async/test_page_request_fallback.py
Closes https://github.com/microsoft/playwright-python/pull/1954
Fixes https://github.com/microsoft/playwright-python/issues/1953
Relates https://github.com/microsoft/playwright-python/issues/2174
> chore: use Sequence for input List like types

- .pre-commit-config.yaml
- local-requirements.txt
- playwright/_impl/_locator.py
- playwright/_impl/_network.py
- pyproject.toml
- scripts/documentation_provider.py
- tests/async/test_browsercontext_add_cookies.py
- tests/async/test_browsercontext_events.py
- tests/async/test_browsercontext_proxy.py
- tests/async/test_browsertype_connect.py
- tests/async/test_download.py
- tests/async/test_fetch_browser_context.py
- tests/async/test_har.py
- tests/async/test_interception.py
- tests/async/test_navigation.py
- tests/async/test_network.py
- tests/async/test_page.py
- tests/async/test_page_network_response.py
- tests/async/test_page_request_intercept.py
- tests/async/test_proxy.py
- tests/server.py
- tests/sync/test_browsercontext_events.py
- tests/sync/test_page_request_intercept.py
https://github.com/microsoft/playwright-python/issues/2174
> chore: refactor TestServer/Request class

- playwright/_impl/_frame.py
This bad `cast()` was introduced either in 1.39.0 or 1.40.0 (probably 1.40.0) - 1.38.0 works.
Fixes [#2215](https://github.com/microsoft/playwright-python/issues/2215).
> fix #2215 (NameError in /_impl/frame.py)

- playwright/_impl/_browser_type.py
- playwright/_impl/_element_handle.py
- playwright/_impl/_locator.py
- playwright/_impl/_page.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
Fixes https://github.com/microsoft/playwright-python/issues/2204
> fix: mask_color for screenshots

- playwright/_impl/_assertions.py
- tests/async/test_assertions.py
Fixes https://github.com/microsoft/playwright-python/issues/2220
Python / JavaScript are dynamically typed languages, so this is only required there and not in .NET/Java.
> fix: throw in expect() if unsupported type is passed to text matcher

- meta.yaml
- setup.py
Dear lovely maintainers of Playwright,
first of all, a happy new year 🍀, and thank you so much for conceiving and maintaining this excellent piece of software.
Coming from https://github.com/crate/cratedb-examples/pull/217#pullrequestreview-1807657044, we discovered that the `greenlet` package in version 3.0.1 breaks Apache Superset, tripping a segmentation fault. Thus, it is not possible to install both Playwright and Apache Superset into the same virtualenv without further ado.
This patch fixes the problem by upgrading to greenlet version 3.0.3.
With kind regards,
Andreas.
> fix: Update to greenlet 3.0.3

- README.md
- playwright/_impl/_browser_context.py
- playwright/_impl/_element_handle.py
- playwright/_impl/_har_router.py
- playwright/_impl/_helper.py
- playwright/_impl/_locator.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/_impl/_set_input_files_helpers.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/conftest.py
- tests/async/test_asyncio.py
- tests/async/test_browsercontext.py
- tests/async/test_browsercontext_request_fallback.py
- tests/async/test_browsercontext_route.py
- tests/async/test_expect_misc.py
- tests/async/test_har.py
- tests/async/test_keyboard.py
- tests/async/test_page_route.py
- tests/async/test_unroute_behavior.py
- tests/sync/test_sync.py
- tests/sync/test_unroute_behavior.py
Fixes https://github.com/microsoft/playwright-python/issues/2176
> chore(roll): roll to Playwright 1.41.0-beta-1705101589000

- .azure-pipelines/publish.yml
Doing the same as in https://github.com/microsoft/playwright-browsers/compare/a2078c881d89ae334ee6609b86e39f48c1cd653c...c4b851fa133aaf6097cd4d6fa3c7e7bbb53bf800.
> devops: migrate to 1ES PT templates

- .azure-pipelines/guardian/SDL/.gdnsuppress
- .azure-pipelines/publish.yml
See here: https://dev.azure.com/securitytools/SecurityIntegration/_wiki/wikis/Guardian/1385/Suppressions
The `.gdnsuppress` file got obtained during a previous test-run where it was in the artifacts section of the SDL stage. They are like `.eslintignore`, but instead of the file location, they contain the location, type, reason etc. in a hashed form, for security reasons.
> devops: suppress test artifact SDL warnings

- tests/async/test_selector_generator.py
**Motivation:** This will make the Docker tests green.
**Investigation notes:**
The issue was that we changed the testID for the selectors in the `test_should_use_data_test_id_in_strict_errors` test while it was used in the `test_locators_should_support_locator_and` test.
This will reset them inside the test for now. Other languages will reset it in the test-runner, but since in Playwright for Python we don't use our `pytest-playwright` plugin for our internal tests, I'll do the encapsulated fix for now.
> test: unflake test_locators_should_support_locator_and

- .gitignore
- playwright/_impl/_errors.py
- tests/async/test_click.py
Addressing issue [#1495](https://github.com/microsoft/playwright-python/issues/1495).
Note, depending on the  Python implementation `__builtins__` references either the module `builtins` or the dictionary `builtins.__dict__`. ([Ref](https://docs.python.org/3/library/builtins.html)). Therefore, I am importing `TimeoutError` as `TimeOutErrorBuiltin` from `builtins` to account for this implementation detail.
Additionally, I modified `.gitignore` to ignore Pipenv artifacts.
> feat: make `TimeoutError` extend  `builtins.TimeoutError`

- .gitignore
- playwright/_impl/_errors.py
- tests/async/test_click.py
This reverts commit 8cd06e5190d8da8c3e6920596e5fc377d6a88c42.
We decided that the risk which it introduces overweights the issues it solves, since there is a working workaround.
> Revert "feat: make `TimeoutError` extend  `builtins.TimeoutError` (#2297)"

- playwright/_impl/_sync_base.py
- tests/sync/conftest.py
- tests/sync/test_sync.py
Motivation: Don't pollute core library, having a single-use function for tests inside our tests directory is much better.
> test: move SyncBase._gather into tests

- playwright/_impl/_page.py
Motivation:
```
Task exception was never retrieved
future: <Task finished name='Task-9032' coro=<Connection.wrap_api_call() done, defined at /home/runner/work/playwright-python/playwright-python/playwright/_impl/_connection.py:481> exception=TargetClosedError('Target page, context or browser has been closed')>
Traceback (most recent call last):
File "/home/runner/work/playwright-python/playwright-python/playwright/_impl/_connection.py", line 490, in wrap_api_call
return await cb()
^^^^^^^^^^
File "/home/runner/work/playwright-python/playwright-python/playwright/_impl/_page.py", line 673, in _update_interception_patterns
await self._channel.send(
File "/home/runner/work/playwright-python/playwright-python/playwright/_impl/_connection.py", line 58, in send
return await …
```
> fix: ignore exceptions from updateInterceptorPatterns

- playwright/_impl/_browser_context.py
- playwright/_impl/_connection.py
- playwright/_impl/_helper.py
- playwright/_impl/_page.py
- tests/async/test_browsercontext_request_intercept.py
- tests/sync/test_browsercontext_request_intercept.py
Issue: Exceptions which will get thrown in route handlers after route.{fulfill,continue,abort} got called,
won't get surfaced to the user in the sync and async version of Playwright for Python.
Scope: Event handlers which use asyncio.create_task
- {BrowserContext,Page}.on("route")
- {Page}.on({"route", "locatorHandlerTriggered"})
There were multiple issues in the implementation:
1. `playwright/_impl/_helper.py` (sync only): we were only waiting until a handler's {continue,fulfill,abort} got called, and did not wait until the actual callback completed. Fix: Wait until the handler completed.
2. `playwright/_impl/_connection.py:423` (sync only): We call event listeners manually, this means that `pyee`'s `"error"` event is not working there. Fix: attach a done callback manually, like pyee is …
> fix: report route handler errors to the user after they completed

- playwright/_impl/_js_handle.py
- tests/async/test_assertions.py
- tests/async/test_evaluate.py
- tests/async/test_jshandle.py
- tests/sync/test_assertions.py
Motivation: This makes datetime with non-UTC timezone objects
> fix: datetime parsing with non-UTC timezones

- playwright/__main__.py
- playwright/_impl/_driver.py
- playwright/_impl/_transport.py
- playwright/async_api/_context_manager.py
- playwright/sync_api/_context_manager.py
Fixes https://github.com/microsoft/playwright-python/issues/2364
Fixes https://github.com/microsoft/playwright-python/issues/2228
Essentially the same as https://github.com/microsoft/playwright-dotnet/pull/2786.
See https://github.com/microsoft/playwright-python/issues/2228#issuecomment-1894955437 for more information.
> fix: get rid of driver wrapper

- playwright/_impl/_async_base.py
- playwright/_impl/_sync_base.py
Looking at the class we are [inheriting from](https://github.com/python/cpython/blob/63d6f2623ef2aa90f51c6a928b96845b9b380d89/Lib/contextlib.py#L41), this should not have any negative side effects.
Fixes https://github.com/microsoft/playwright-python/issues/2368
> fix: inherit expect context managers from contextlib

- playwright/_impl/_connection.py
- playwright/_impl/_errors.py
- playwright/_impl/_helper.py
- tests/async/test_browsercontext.py
- tests/async/test_frames.py
- tests/async/test_keyboard.py
- tests/async/test_locators.py
- tests/async/test_network.py
- tests/async/test_queryselector.py
- tests/sync/test_locators.py
- tests/sync/test_queryselector.py
This makes the error message more aligned to how to is in Node.js:
```
node:internal/process/promises:289
triggerUncaughtException(err, true /* fromPromise */);
^
locator.click: Timeout 2000ms exceeded.
Call log:
- waiting for getByRole('link', { name: 'More asdfasdfinformation' })
at /Users/maxschmitt/Developer/playwright/test.mjs:28:70 {
name: 'TimeoutError'
}
Node.js v20.9.0
```
```
tests/async/test_locators.py::test_locator_click_timeout_error_should_contain_call_log[chromium] Traceback (most recent call last):
File "/Users/maxschmitt/Developer/playwright-python/tests/async/test_locators.py", line 1090, in test_locator_click_timeout_error_should_contain_call_log
await page.get_by_role("button", name="Hello Python").click(timeout=42)
File …
```
> fix: brush up exception messages to include apiName & call log

- playwright/__main__.py
130 means Command terminated by user, this matches it what happens with `npx playwright ...`.
> fix(cli): don't show a stack trace when command + c of the CLI

- playwright/_impl/_page.py
- tests/async/test_video.py
Before it was a `Video` instance which had no capabilities, it was throwing on every call, e.g. save_as or delete.
Aligning it with upstream.
> fix: page.video should be None if not recording

- playwright/_impl/_cdp_session.py
Following our protocol spec: https://github.com/microsoft/playwright/blob/82aefd24db1ba9977c3f6953347ee266845790ea/packages/protocol/src/protocol.yml#L3110
> fix(cdpSession): allow optional params in events

- playwright/_impl/_connection.py
Fixes https://github.com/microsoft/playwright-python/issues/2426
Mirror of: https://github.com/microsoft/playwright-python/blob/5b6461884286172202f7f8ed875330f83c97abcf/playwright/_impl/_connection.py#L371-L374
> fix(connect): Future exception was never retrieved on close()

- playwright/_impl/_driver.py
- playwright/_impl/_transport.py
this PR will prepare playwright to make it easier to be compiled into standalone / onefile programs for ease of distribution
the following changes have been made:
1) added the python version of 
```js
const registryDirectory = exports.registryDirectory
```
in `playwright._impl._driver`, Nuitka will use this to resolve the path to the browsers .
2) check if `_compiled__` is in the globals dict, if it is, set `PLAYWRIGHT_BROWSERS_PATH` to 0 just like for pyinstaller
> prepare support for Nuitka

- playwright/_impl/_driver.py
Adds the ability to use the env variable on win32 PLAYWRIGHT_NODEJS_PATH to use local nodejs
> fix(driver): consider PLAYWRIGHT_NODEJS_PATH from host env win32

- README.md
- playwright/_impl/_api_structures.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_clock.py
- playwright/_impl/_fetch.py
- playwright/_impl/_helper.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/_impl/_set_input_files_helpers.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/documentation_provider.py
- scripts/generate_api.py
- setup.py
- tests/assets/input/folderupload.html
- tests/async/conftest.py
- tests/async/test_browsercontext_add_cookies.py
- tests/async/test_browsercontext_cookies.py
- tests/async/test_browsercontext_events.py
- tests/async/test_browsertype_connect.py
- tests/async/test_defaultbrowsercontext.py
- tests/async/test_fetch_browser_context.py
- tests/async/test_fetch_global.py
- tests/async/test_input.py
- tests/async/test_network.py
- tests/async/test_page_clock.py
- tests/async/test_request_continue.py
- tests/sync/test_locators.py
- tests/sync/test_page_clock.py
- tests/utils.py
https://github.com/microsoft/playwright-python/issues/2455
> chore(roll): roll Playwright to 1.45.0-alpha-2024-06-14

- README.md
- playwright/_impl/_clock.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/documentation_provider.py
- setup.py
- tests/async/test_page_clock.py
- tests/sync/test_page_clock.py
`fromtimestamp` and `timestamp()` both return float's - so choosing a float seems more reasonable here.
> chore(roll): roll to Playwright v1.45.0-beta-1719505820000

- README.md
- playwright/_impl/_api_structures.py
- playwright/_impl/_element_handle.py
- playwright/_impl/_fetch.py
- playwright/_impl/_frame.py
- playwright/_impl/_network.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_browsercontext_client_certificates.py
- tests/async/test_fetch_browser_context.py
- tests/sync/test_browsercontext_client_certificates.py
- tests/sync/test_fetch_browser_context.py
Corresponding upstream PR wich was required to make doclint pass: https://github.com/microsoft/playwright/pull/32516
Fixes https://github.com/microsoft/playwright-python/issues/2497
> chore(roll): roll Playwright to v1.47.0

- .github/workflows/ci.yml
- meta.yaml
- setup.py
Fixes https://github.com/microsoft/playwright-python/issues/2564
Closes https://github.com/microsoft/playwright-python/pull/2562
> chore: support Python 3.13

- .pre-commit-config.yaml
- local-requirements.txt
- playwright/_impl/_assertions.py
- playwright/_impl/_async_base.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_connection.py
- playwright/_impl/_impl_to_api_mapping.py
- playwright/_impl/_js_handle.py
- playwright/_impl/_json_pipe.py
- playwright/_impl/_sync_base.py
- playwright/async_api/__init__.py
- playwright/async_api/_generated.py
- playwright/sync_api/__init__.py
- playwright/sync_api/_generated.py
- pyproject.toml
- scripts/documentation_provider.py
- setup.cfg
- tests/async/test_accessibility.py
- tests/async/test_keyboard.py
- tests/async/test_page_route.py
- tests/server.py
- tests/sync/test_accessibility.py
- tests/test_reference_count_async.py
Fixes https://github.com/microsoft/playwright-python/issues/2582
Recent VSCode versions were using more recent versions of Pyright which was showing errors. This updates our linter setup.
> chore: update linters 2024

- playwright/_impl/_connection.py
- tests/async/test_asyncio.py
Fixes https://github.com/microsoft/playwright-python/issues/2581
> fix(asyncio): already cancelled tasks ends up in 'InvalidStateError: invalid state'

- CONTRIBUTING.md
The link in the below line
For more details look at the [CI configuration](https://github.com/microsoft/playwright-python/blob/main/blob/main/.github/workflows/ci.yml).
is incorrect since it has repeated /blob/main/ in its url. 
I have removed the repeated '/blob/main' so that the link has the right URL.
For more details look at the [CI configuration](https://github.com/microsoft/playwright-python/blob/main/.github/workflows/ci.yml).
> chore: Fix broke CI configuration link

- playwright/_impl/_assertions.py
- tests/async/test_assertions.py
- tests/sync/test_assertions.py
Fixes https://github.com/microsoft/playwright-python/issues/2616
drive-by: align more sync tests with async.
> fix(assertions): error messages from negated matchers

- .azure-pipelines/publish.yml
- .github/workflows/ci.yml
- meta.yaml
- pyproject.toml
- setup.py
Python 3.8 is EOL since this month and a bunch of our dependencies dropped support for it as well, so we can't stay on their recent versions.
> chore: drop Python 3.8

- local-requirements.txt
- pyproject.toml
- tests/async/conftest.py
- tests/conftest.py
They recommend setting it as per [here](https://github.com/pytest-dev/pytest-asyncio/blob/adcae5bea72a9e16b8420d06e23b3915c6f82333/pytest_asyncio/plugin.py#L203-L205). Full changelog see [here](https://pytest-asyncio.readthedocs.io/en/latest/reference/changelog.html).
> test: update pytest-asyncio to 0.24.0

- .github/workflows/publish.yml
Removing since https://github.com/conda/conda-build/issues/5267 is fixed.
Lets see what else is needed to fix https://github.com/microsoft/playwright-python/actions/runs/11441512009/workflow.
> devops: do not pin conda-build

- examples/todomvc/requirements.txt
It should use ToT instead of an old pinned version.
> devops: do not pin pytest-playwright for examples

- playwright/_impl/_connection.py
- tests/async/test_tracing.py
- tests/sync/test_tracing.py
The PR fixes an issue with incorrect `apiName` determination in tracing when using event listeners. Here's what was happening:
When using sync event listeners, the stack trace would include internal implementation details from the `_impl_to_api_mapping` module, which acts as glue between user code and internal code. We expect no other function between the implementation and the user call-side. This caused the API name to be incorrectly determined since these internal frames were being included in the stack analysis.
The key changes:
- Added filtering to skip stack frames from `_impl_to_api_mapping` when extracting stack trace information
- Added test cases for both sync and async event listeners to verify correct API name determination
The async case worked correctly because async event …
> fix(tracing): apiName determination with event listeners

- playwright/_impl/_element_handle.py
- tests/async/test_page_select_option.py
- tests/sync/test_page_select_option.py
Fixes https://github.com/microsoft/playwright-python/issues/2659
> fix(select): handle empty values and labels in select options

- README.md
- playwright/_impl/_api_structures.py
- playwright/_impl/_assertions.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_frame.py
- playwright/_impl/_helper.py
- playwright/_impl/_locator.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/_impl/_tracing.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/generate_api.py
- setup.py
- tests/async/test_browsercontext.py
- tests/async/test_emulation_focus.py
- tests/async/test_network.py
- tests/async/test_page_aria_snapshot.py
- tests/async/test_route_web_socket.py
- tests/async/test_tracing.py
- tests/async/test_websocket.py
- tests/conftest.py
- tests/server.py
- tests/sync/test_network.py
- tests/sync/test_page_aria_snapshot.py
- tests/sync/test_route_web_socket.py
- tests/sync/test_tracing.py
Fixes https://github.com/microsoft/playwright-python/issues/2606
Fixes https://github.com/microsoft/playwright-python/issues/1949
> chore: roll to v1.49.0

- setup.py
Since https://github.com/microsoft/playwright-python/commit/4fd5de05438f31990d4612c1dd9252da86e34155 the produced wheels contained the source as `deflate` and the driver as `store` compressed files. This resulted in a very large wheel file which wasn't accepted by Pypi.
This uses deflated everywhere.
> devops: make wheels smaller (use deflate zip compression)

- setup.py
`shutil.move("wheelhouse", self.dist_dir)` nests `wheelhouse` directory itself inside of `dist/.tmp-XXX` instead of moving its contents there.
That results in wheel with incorrect `RECORD` contents to end up in `dist` folder, which is then published.
Move wheel with drivers and incorrect `RECORD` to `wheelhouse` and make `auditwheel` to put corrected wheel to `dist/.tmp-XXX`.
Then remove `wheelhouse` folder.
Below are snapshots of dist and wheelhouse folder contents for comparison.
Note: hashes were shrunk and some output removed for readability sake
```
@@@ before-auditwheel
d79a094  ./dist/.tmp-bz7ar00j/playwright-1.49.1.dev2+g3f04396.d20241126-py3-none-manylinux1_x86_64.whl
@@@ after-auditwheel
ee22f99  ./wheelhouse/playwright-1.49.1.dev2+g3f04396.d20241126-py3-none-manylinux1_x86_64.wh …
```
> Fix build process producing wheels with incorrect RECORD

- playwright/_impl/_helper.py
- tests/async/test_route_web_socket.py
- tests/sync/test_route_web_socket.py
https://github.com/microsoft/playwright-python/issues/2686
> fix(webSocketRoute): allow no trailing slash in route matching

- .azure-pipelines/publish.yml
Fixes https://github.com/microsoft/playwright-internal/issues/233
> devops: use separate Release job for publishing

- .github/workflows/ci.yml
- meta.yaml
This PR modifies our conda package configuration to use `noarch: python` in our meta.yaml. This change will help us distribute a single package that works across all Python versions (>=3.9 as specified in our requirements) instead of creating separate packages for each Python version.
Key changes:
- Added `noarch: python` to meta.yaml build configuration 
- Updated CI workflow to use Python 3.12 for building (the build Python version becomes less relevant with noarch. Align it tho between out test and publish workflows)
- Added explicit miniconda-version: latest to ensure consistent builds (align between test/publish workflows)
Background:
Previously, our conda packages were being built specifically for each Python version (e.g., py39, py312, py313), which made distribution and …
> devops: add noarch support to meta.yaml

- .github/workflows/test_docker.yml
- local-requirements.txt
- tests/async/test_browsercontext_proxy.py
- tests/async/test_browsertype_connect.py
- tests/async/test_input.py
- tests/async/test_network.py
- tests/async/test_resource_timing.py
- tests/async/test_websocket.py
- tests/async/test_worker.py
- tests/conftest.py
- tests/sync/test_resource_timing.py
This PR changes our assumption from marking individual tests as flaky to marking the whole test run as flaky and retrying all the tests if needed. It replaces the flaky plugin with rerunfailures plugin (maintained by the pytest org) since its not compatible [with each-other](https://pypi.org/project/pytest-rerunfailures/#compatibility). This aligns it how we do it in Node.js.
It enables 3 retries only for CI runs.
> test: migrate flaky plugin to rerunfailures

- local-requirements.txt
- pyproject.toml
- tests/async/conftest.py
This PR does not include any user-facing changes - its only about our tests. There it updates the `pytest-asyncio` plugin and leverages the new config option which simplifies it.
Relates https://github.com/microsoft/playwright-python/issues/2742.
> chore: update pytest-asyncio

- playwright/_impl/_browser_type.py
There is a bug in Python 3.9 on Windows that when you try to resolve `'foobar'` it stays `'foobar'`. Python 3.9+ has it fixed. Since we consider `''` in `userDataDir` as our public API lets workaround the bug for now.
> fix: "" userDataDir on Windows with Python 3.9

- playwright/_impl/_connection.py
Looks like this was changed [here](https://github.com/microsoft/playwright/commit/2a3d67195dff6ece12bd36aab970a1fc95776998#diff-b6f15e1e595e78791af29171502861070168d93fac02cdd83fd8d99d535e9540L137). Relates https://github.com/microsoft/playwright-dotnet/issues/3132
Before:
```
Traceback (most recent call last):
File "/Users/maxschmitt/Developer/playwright-python/test.py", line 30, in <module>
asyncio.run(main())
File "/Users/maxschmitt/.pyenv/versions/3.12.0/lib/python3.12/asyncio/runners.py", line 194, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "/Users/maxschmitt/.pyenv/versions/3.12.0/lib/python3.12/asyncio/runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> chore: fix double call log formatting

- README.md
- playwright/_impl/_assertions.py
- playwright/_impl/_fetch.py
- playwright/_impl/_js_handle.py
- playwright/_impl/_locator.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_accessibility.py
- tests/async/test_assertions.py
- tests/async/test_fetch_global.py
- tests/async/test_page_aria_snapshot.py
- tests/async/test_page_clock.py
- tests/async/test_page_evaluate.py
- tests/sync/test_accessibility.py
- tests/sync/test_assertions.py
- tests/sync/test_fetch_global.py
- tests/sync/test_page_aria_snapshot.py
- tests/sync/test_page_clock.py
Roll to server 1.52.0. Glob changes (https://github.com/microsoft/playwright/pull/34923, https://github.com/microsoft/playwright/pull/35136) will come in a subsequent PR due to their relative complexity.
> chore(roll): roll Playwright to 1.52.0 (omitting glob changes)

- setup.py
What is it solving? Before this change Playwright for Python was not able to run on `win32-arm64` since we don't publish a wheel on that platform. The install via PIP was failing. In Node.js its already working since Windows emulates all the arm64 instructions. This patch adds a new wheel using a dedicated `win32-arm64` driver (contains also win32-arm64 Node.js) in order to make Playwright work there.
Relates https://github.com/microsoft/playwright/pull/35185
This requires a new roll to make the Docker tests pass.
> chore: publish win32-arm64 wheel

- playwright/_impl/_glob.py
- playwright/_impl/_helper.py
- playwright/_impl/_network.py
- tests/async/test_page_route.py
- tests/async/test_request_intercept.py
- tests/sync/test_request_intercept.py
Continuation of #2823, addressing the changes is https://github.com/microsoft/playwright/pull/34923 and https://github.com/microsoft/playwright/pull/35136.
> chore(roll): roll glob changes from Playwright 1.52.0

- local-requirements.txt
- playwright/_impl/_connection.py
- tests/async/test_asyncio.py
- tests/sync/test_sync.py
This PR partially fixes https://github.com/microsoft/playwright-python/issues/2744
This PR makes two changes:
1. Call `inspect.stack(0)` instead of `inspect.stack()`
2. Only call `inspect.stack()` when `getattr(task, "__pw_stack__")` doesn't find a stack in the task
`inspect.stack()` by default requests context for the first frame of the callstack, which is a [very expensive operation](https://stackoverflow.com/a/17407257/132540). We don't use the returned context information, so we can safely use `inspect.stack(context=0)`.
In my testing, this improved the speed of `evaluate()` by about 2.5x:
**Test:**
```py
async def test_speed_test(page: Page) -> None:
start_time = time.time()
for i in range(0, 1000):
await page.evaluate('() => 1 + 1')
print(time.time() - start_time)
```
Before this …
> _connect.py: Don't request context when inspecting stack

- playwright/_impl/_connection.py
- playwright/_impl/_network.py
- playwright/_impl/_path_utils.py
- playwright/_impl/_sync_base.py
Building off of https://github.com/microsoft/playwright-python/pull/2835, this PR replaces the remaining instances of `stack()` with `stack(0)`, so that we avoid getting context information for the first frame of the stack, which is expensive.
I also discovered that we were calling `traceback.format_list(traceback.extract_stack()[-10:])`, which does the following:
1. Extract the entire stack
2. Format the entire stack into strings
3. Throw away everything except for the last 10 formatted frames of the stack
To fix this, I've made `extract_stack()` use the `limit=10` parameter.
Finally, I optimized `_path_utils.py` to only retrieve two frames from the stack, instead of retrieving the entire stack and then discarding everything but the second frame :)
> More stack-related performance improvements

- tests/async/test_browsercontext_storage_state.py
- tests/async/test_browsertype_connect.py
- tests/async/test_chromium_tracing.py
- tests/async/test_defaultbrowsercontext.py
- tests/async/test_download.py
- tests/async/test_fetch_global.py
- tests/async/test_har.py
- tests/async/test_headful.py
- tests/async/test_launcher.py
- tests/async/test_page_base_url.py
- tests/async/test_pdf.py
- tests/async/test_tracing.py
- tests/async/test_video.py
- tests/sync/test_browsercontext_storage_state.py
- tests/sync/test_fetch_global.py
- tests/sync/test_har.py
- tests/sync/test_launcher.py
- tests/sync/test_pdf.py
- tests/sync/test_tracing.py
- tests/sync/test_video.py
Before we were using this:
https://github.com/pytest-dev/pytest/blob/9e9633de9da7a9fab03b4bba3a326bf85b412050/src/_pytest/legacypath.py#L306-L320
We should use this instead:
https://github.com/pytest-dev/pytest/blob/9e9633de9da7a9fab03b4bba3a326bf85b412050/src/_pytest/tmpdir.py#L258-L263
The old one didn't use 'Path' instances which makes trouble sometimes.
> test: use tmp_path instead of tmpdir fixture

- playwright/_impl/_accessibility.py
- playwright/_impl/_artifact.py
- playwright/_impl/_browser.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_cdp_session.py
- playwright/_impl/_clock.py
- playwright/_impl/_connection.py
- playwright/_impl/_dialog.py
- playwright/_impl/_element_handle.py
- playwright/_impl/_fetch.py
- playwright/_impl/_frame.py
- playwright/_impl/_har_router.py
- playwright/_impl/_input.py
- playwright/_impl/_js_handle.py
- playwright/_impl/_json_pipe.py
- playwright/_impl/_local_utils.py
- playwright/_impl/_locator.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/_impl/_selectors.py
- playwright/_impl/_set_input_files_helpers.py
- playwright/_impl/_stream.py
- playwright/_impl/_tracing.py
- playwright/_impl/_waiter.py
- playwright/_impl/_writable_stream.py
Follow up from #2892. Remove implicit timeout information in server calls and make it explicit and required.
> chore: explicit timeout config for send

- playwright/_impl/_locator.py
- playwright/_impl/_page.py
- tests/async/test_locators.py
- tests/async/test_page.py
- tests/sync/test_locators.py
- tests/sync/test_page.py
Fixes #2904 
Ignore `timeout` args passed to any `is_visible()`/`is_hidden()` call.
> fix(api): ignore deprecated timeout arg provided to is_visible/hidden

- playwright/_impl/_async_base.py
- playwright/_impl/_sync_base.py
Updates `AsyncContextManager.__aexit__` and `SyncContextManager.__exit__` to use Optional types for exception parameters (exc_type, exc_val, traceback) to match the standard Python typing protocols.
This aligns with the official type definitions in typeshed where AbstractContextManager and AbstractAsyncContextManager define these parameters as Optional since they are None when no exception occurs.
Ref: https://github.com/python/typeshed/blob/9317dc62bd4fb46b8b48ce5353286cab80308d47/stdlib/contextlib.pyi#L52-L54
Fixes type checker compatibility issues when using BrowserContext with type checkers that enforce strict protocol compliance.
Fixes https://github.com/microsoft/playwright-python/issues/2856
> fix: Make context manager __exit__/__aexit__ signatures compatible with typing protocols

- tests/sync/test_browsercontext_events.py
Fixes https://github.com/microsoft/playwright-python/actions/runs/16736165470/job/47375331127?pr=2933#step:6:860
> test: unflake dialog inline script test

- tests/async/test_defaultbrowsercontext.py
Fixes https://github.com/microsoft/playwright-python/actions/runs/16744062888/job/47398320653?pr=2934#step:8:1601
Similar like we do upstream. We forgot to add the filter call in another test.
Drive-by: Align how we filter to how we do it upstream.
> test: unflake test_context_add_cookies_should_work

- playwright/_impl/_connection.py
Though I encounter this bug totally by accident with hacks, but there is two same lines of code and I don't know what the point is.
I think adding callback once just before sending message is proper.
> fix: remove duplicate callback addition

- tests/sync/test_page_aria_snapshot.py
- tests/sync/test_page_event_console.py
- tests/sync/test_page_event_pageerror.py
- tests/sync/test_page_event_request.py
Add missing sync tests from #2986
> chore: add dupe sync tests for 1.56 roll

- playwright/_impl/_connection.py
- tests/test_reference_count_async.py
Fix memory leak where ProtocolCallback objects accumulated when tracing was enabled. The issue affected both sync and async Playwright, but was more severe in async usage where callbacks persisted permanently.
- When tracing is enabled, send_no_reply() creates ProtocolCallback objects
- These callbacks have circular references via task cancellation handlers
- For no_reply messages, futures are never resolved, preventing GC cleanup
- Each page operation during tracing leaked ~10 callbacks permanently
- Add no_reply parameter to ProtocolCallback constructor
- For no_reply=True: skip cancellation setup and resolve future immediately
- For no_reply=False: use full constructor with cancellation handling
- Update dispatch() to handle missing callbacks gracefully
- Added regression test in …
> fix: prevent ProtocolCallback memory leak during tracing (#2977)
