- .github/workflows/ci.yml
- .gitignore
- driver/package-lock.json
Closes #2
Playwright installation and extraction seems also quite slow.
> devops(ci): cache Node.js PKG path

- playwright_web/frame.py
> fix: page.getAttribute was not working

- .github/workflows/ci.yml
- local-requirements.txt
- playwright/playwright.py
- setup.py
- As discussed: https://github.com/microsoft/playwright-python/pull/14#issuecomment-655218929 fixes also a bug on Windows.
- Adds more classifiers for project visibility
- fixes build step in CI which was [broken](https://github.com/microsoft/playwright-python/runs/848682505#step:9:11) on master
> ci: test also on Python 3.7

- .github/workflows/ci.yml
- tests/conftest.py
- tests/test_element_handle.py
Firefox and Chromium should pass. WebKit was not passing locally.
> tests: run on all browser engines

- setup.cfg
- tests/conftest.py
- tests/test_pdf.py
WebKit CI failure seems like a it's flaky and by that not related.
> tests: added for Page.pdf

- tests/assets/dummy_bad_browser_executable.js
- tests/conftest.py
- tests/test_launcher.py
Marked two test cases as skipped. Let's try to fix them at some day, added also a TODO comment, so we find them easier.
> tests: added launcher tests

- playwright/page.py
- playwright/worker.py
- tests/assets/worker/worker.html
- tests/assets/worker/worker.js
- tests/test_network.py
- tests/test_worker.py
added tests for the `worker.spec.js`. One test is not working for Firefox, probably something for you, skipping it for now :)
> test: added worker tests

- playwright/__init__.py
- playwright/js_handle.py
- playwright/object_factory.py
- playwright/playwright.py
- playwright/selectors.py
- tests/assets/sectionselectorengine.js
- tests/conftest.py
- tests/test_queryselector.py
- tests/utils.py
Closes #71
`tests/test_worker.py::test_workers_should_clear_upon_navigation[firefox]` is failing but its unrelated and seems like it's flaky.
> feat: added selector engine

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- buildbots/test-sync-generation.sh
Since its getting a core component of the project it useful to check it on the buildbots and verify that the latest version (output) matches the current file in the repo.
> devops(bots): test sync generation script

- README.md
- build_driver.py
> chore(build-driver): auto update README on roll

- README.md
- driver/package.json
- local-requirements.txt
- playwright/browser_type.py
- playwright/connection.py
- playwright/drivers/browsers.json
- playwright/frame.py
- playwright/sync.py
- tests/conftest.py
- tests/test_browsercontext.py
- tests/test_element_handle.py
- tests/test_interception.py
- tests/test_launcher.py
- tests/test_network.py
> tests: added skipped tests back

- .github/workflows/ci.yml
- playwright/__main__.py
- playwright/browser_type.py
- playwright/helper.py
- playwright/main.py
Fix for https://github.com/microsoft/playwright-python/issues/21
> feat(install): introduce explict post-installation step

- tests/async/test_dialog.py
- tests/async/test_focus.py
A small follow up MR for my last contributions.
> chore: test cleanups

- playwright/async_api.py
- playwright/network.py
- playwright/sync_api.py
- tests/async/test_network.py
> feat: aded Request.postDataJSON

- playwright/async_api.py
- playwright/download.py
- playwright/sync_api.py
- tests/async/test_download.py
> feat: added Download.saveAs(path)

- playwright/async_api.py
- playwright/browser.py
- playwright/sync_api.py
- tests/async/test_browser.py
> tests: added browser tests

- playwright/main.py
> fix: stderr redirect with monkeypatched stderr

- playwright/async_api.py
- playwright/browser_context.py
- playwright/browser_type.py
- playwright/download.py
- playwright/element_handle.py
- playwright/frame.py
- playwright/page.py
- playwright/selectors.py
- playwright/sync_api.py
Sounds like merge conflicts. Feel free to land dgozman changes first.
> fix: support Path objects in Page.screenshot

- playwright/browser_type.py
- tests/async/test_issues.py
> fix(browser_type): ignoreDefaultArgs in launch()

- .github/workflows/deploy-docs.yml
- playwright/__init__.py
- scripts/postPdoc3Generation.js
> docs: adjust style of the landing page

- playwright/async_api.py
- playwright/browser.py
- playwright/sync_api.py
- tests/async/test_issues.py
> fix(context): allow defaultBrowserType keyword

- setup.py
Flask does it too in that way: https://github.com/pallets/flask/blob/master/setup.py
> chore: dependencies great than instead of hard pin

- playwright/async_api.py
- playwright/async_base.py
- playwright/page.py
- playwright/sync_api.py
- playwright/sync_base.py
- scripts/generate_async_api.py
- scripts/generate_sync_api.py
- tests/async/test_listeners.py
- tests/sync/test_listeners.py
Fixes https://github.com/microsoft/playwright-python/issues/269
> fix(listeners): fix removing listeners

- .github/workflows/ci.yml
Should show us if it works or not right now.
> devops: test on macOS Big Sur

- build_package.py
Fixes https://github.com/microsoft/playwright-python/issues/304
> chore: bake macosx_11_0_x86_64 wheel

- setup.py
Fixes https://github.com/microsoft/playwright-python/issues/242
> chore: explicitly use greenlet 1.0a1

- playwright/async_api.py
- playwright/sync_api.py
- scripts/generate_async_api.py
- scripts/generate_sync_api.py
Fixes https://github.com/microsoft/playwright-python/issues/289
> chore: add expect_* context manager docstrings

- playwright/accessibility.py
- playwright/connection.py
- playwright/file_chooser.py
- playwright/input.py
- playwright/main.py
- playwright/sync_api.py
- playwright/sync_base.py
- playwright/transport.py
- playwright/video.py
- scripts/generate_sync_api.py
- tests/server.py
- bubbles the run_until_complete to main.py
- creates loop if missing
- removes dispatcher greenlet singleton
> fix(loop): greenlet + async code health code

- playwright/_transport.py
> chore(stderr): fix handling without stderr fileno

- playwright/__main__.py
- setup.py
A rebaseline for https://github.com/microsoft/playwright-python/pull/371
> feat: add cli `playwright` as an entry point.

- playwright/async_api/__init__.py
- playwright/async_api/_generated.py
- playwright/sync_api/__init__.py
- playwright/sync_api/_generated.py
- scripts/generate_api.py
https://github.com/microsoft/playwright-python/issues/466
> chore: enforce keyword-only arguments

- playwright/_impl/_transport.py
> fix: stderr forward if no stderr exists

- scripts/documentation_provider.py
Python side of https://github.com/microsoft/playwright/pull/5238
> docs(gen): forcing event names to be lowercase

- README.md
We are out of alpha and now stable, should be fine.
> docs(readme): install stable package version with pip

- playwright/_impl/_network.py
- tests/async/test_network.py
> fix(postData): do not require content type when retrieving post data

- playwright/__main__.py
- playwright/_impl/_transport.py
- tests/async/test_launcher.py
- tests/async/test_page.py
drive-by removed workarounds for pkg.
> test: enable skipped tests

- tests/async/test_launcher.py
caused by the past two PRs which were conflicting
> tests: fixed executable path tests

- setup.py
cURL lead to OpenSSL errors before.
Lets see if it performs now better.
> build: download files from CDN with urlretrieve

- playwright/_impl/_browser.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_console_message.py
- playwright/_impl/_dialog.py
- playwright/_impl/_download.py
- playwright/_impl/_file_chooser.py
- playwright/_impl/_frame.py
- playwright/_impl/_impl_to_api_mapping.py
- playwright/_impl/_js_handle.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/_impl/_video.py
- tests/async/test_download.py
- tests/async/test_input.py
- tests/async/test_jshandle.py
- tests/async/test_network.py
- tests/async/test_websocket.py
- tests/async/test_worker.py
- tests/sync/test_sync.py
- tests/sync/test_video.py
> feat: Repr for classes

- .dockerignore
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .gitignore
- scripts/postPdoc3Generation.js
- scripts/update_versions.py
Remove redundant build files .
> build: Remove redundant build files

- playwright/_impl/_connection.py
- playwright/_impl/_wait_helper.py
- setup.py
FIxes https://github.com/microsoft/playwright/issues/6223
> fix: Rename name to api_name

- .github/workflows/ci.yml
- tests/async/test_network.py
- tests/sync/test_element_handle_wait_for_element_state.py
> devops: upload test logs on failure

- .github/workflows/ci.yml
- local-requirements.txt
- playwright/_impl/_browser.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_connection.py
- playwright/_impl/_page.py
- playwright/_impl/_transport.py
- playwright/_impl/_video.py
- playwright/async_api/_context_manager.py
- playwright/async_api/_generated.py
- playwright/sync_api/_context_manager.py
- playwright/sync_api/_generated.py
- scripts/expected_api_mismatch.txt
- setup.cfg
- setup.py
- tests/async/test_browsertype_connect.py
- tests/conftest.py
- tests/sync/test_browsertype_connect.py
Closes #529
Quite an early implementation, need to think about the last skipped test.
> feat: added BrowserType.connect

- playwright/_impl/_api_types.py
- playwright/_impl/_helper.py
- tests/async/test_page.py
https://github.com/microsoft/playwright/pull/5970
> feat(pageerror): added Error.name property support

- .pre-commit-config.yaml
- local-requirements.txt
- pyproject.toml
- setup.py
Fixes https://github.com/microsoft/playwright-python/issues/668
> fix: fix broken deps for PEP 517

- playwright/_impl/_browser_type.py
- playwright/_impl/_transport.py
- playwright/_impl/_wait_helper.py
- playwright/async_api/_context_manager.py
- playwright/sync_api/_context_manager.py
- tests/async/test_browsertype_connect.py
- tests/sync/test_browsertype_connect.py
> fix(transport): handle connection error correctly

- tests/async/test_click.py
Was done upstream the same way at some day.
> test: unflake test_timeout_waiting_for_stable_position test

- playwright/_impl/_js_handle.py
- tests/async/test_evaluate.py
> chore: serialize None into null instead of undefined

- README.md
https://github.com/microsoft/playwright-python/issues/689#issuecomment-841632670
> docs: add note about time.sleep

- playwright/_impl/_browser_context.py
- tests/assets/simple-extension/content-script.js
- tests/assets/simple-extension/index.js
- tests/assets/simple-extension/manifest.json
- tests/async/test_launcher.py
Relates #689
And applied upstream https://github.com/microsoft/playwright/pull/4018
> test: add test for extension testing

- README.md
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
Extracted from https://github.com/microsoft/playwright-python/pull/717
> feat(roll): roll Playwright to 1.12.0-next-1621639045000

- playwright/_impl/_connection.py
- playwright/_impl/_tracing.py
- tests/async/test_browsercontext.py
- tests/async/test_browsertype_connect_cdp.py
- tests/async/test_defaultbrowsercontext.py
- tests/async/test_download.py
- tests/async/test_frames.py
- tests/async/test_headful.py
- tests/async/test_network.py
- tests/async/test_page.py
- tests/async/test_tracing.py
- tests/async/test_video.py
- tests/async/test_worker.py
- tests/conftest.py
- tests/server.py
- tests/sync/test_browsertype_connect_cdp.py
- tests/sync/test_video.py
Applied:
- https://github.com/microsoft/playwright/pull/3742
- https://github.com/microsoft/playwright/pull/6444
First iteration for reducing flaky tests, will follow up with more.
> tests: cleanup tests

- .github/ISSUE_TEMPLATE/bug.md
- playwright/__main__.py
Added `playwright envinfo` command to auto capture the required system info.
> chore: add bug issue template

- README.md
- playwright/_impl/_browser_type.py
- playwright/_impl/_helper.py
- playwright/_impl/_page.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_websocket.py
~~Blocked by https://github.com/microsoft/playwright/pull/6809~~
> feat(roll): roll Playwright to 1.12.0-next-1622429176000

- setup.py
This should fix the flaky tracing tests.
> feat(roll): roll Playwright to 1.12.0-next-1623050602000

- playwright/_impl/_network.py
- tests/async/test_websocket.py
> fix(websocket): error handling

- README.md
Some people don't know what TypeScript is.
> docs: fixed wrong links

- playwright/_impl/_cdp_session.py
- tests/sync/test_cdp_session.py
Fiixes https://github.com/microsoft/playwright-python/issues/776
> fix(cdp): fix cdp session, add tests

- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/generate_async_api.py
- scripts/generate_sync_api.py
> feat: support dynamic browser name

- README.md
- playwright/_impl/_api_structures.py
- playwright/_impl/_element_handle.py
- playwright/_impl/_frame.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/generate_api.py
- setup.py
- tests/async/test_element_handle.py
- tests/async/test_network.py
- tests/async/test_page.py
- tests/async/test_resource_timing.py
- tests/async/test_websocket.py
- tests/sync/test_element_handle.py
- tests/sync/test_network.py
- tests/sync/test_page.py
- tests/sync/test_resource_timing.py
> feat(roll): roll Playwright to 1.13.0-next-1625101008000

- playwright/_impl/_browser_context.py
- playwright/_impl/_page.py
- tests/async/test_browsercontext.py
- tests/async/test_interception.py
This PR mirrors https://github.com/microsoft/playwright/pull/7585
https://github.com/microsoft/playwright/issues/7394
> fix: reverse route handlers order

- playwright/_impl/_browser.py
- playwright/_impl/_browser_type.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_browsercontext.py
> feat(roll): roll Playwright 1.14.0-1629408981000

- ROLLING.md
This docs has instructions on how to roll to Playwright driver
> doc: add rolling.md

- README.md
- playwright/_impl/_api_structures.py
- playwright/_impl/_browser.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_element_handle.py
- playwright/_impl/_frame.py
- playwright/_impl/_helper.py
- playwright/_impl/_locator.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/_impl/_tracing.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_accessibility.py
- tests/async/test_browsercontext.py
- tests/async/test_network.py
- tests/async/test_page.py
- tests/sync/test_accessibility.py
- tests/sync/test_page.py
https://github.com/microsoft/playwright/pull/8632
> feat(roll): roll Playwright 1.15.0-next-1631091227000

- playwright/_impl/_page.py
- tests/async/test_page.py
https://github.com/microsoft/playwright/issues/8820
> fix: make sure page.goto navigates away from pages with beforeunload

- playwright/_impl/_browser_context.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/_impl/_video.py
- setup.cfg
- tests/sync/test_browsertype_connect.py
> test: re-enable type checking on sync tests

- setup.py
This includes Node.js 14 driver.
> feat(roll): roll Playwright 1.16.0-next-1631799458000

- README.md
- playwright/_impl/_frame.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_element_handle.py
- tests/async/test_page.py
- tests/sync/test_element_handle.py
Fixes https://github.com/microsoft/playwright-python/issues/912
> feat(roll): roll Playwright 1.16.0-next-1632717011000

- playwright/_impl/_connection.py
- tests/common/test_events.py
Fixes https://github.com/microsoft/playwright-python/issues/873
> fix: propagate dispatch error to current task

- README.md
- playwright/_impl/_browser_context.py
- playwright/_impl/_helper.py
- playwright/_impl/_page.py
- setup.py
> chore: roll to Playwright 1.16.0-next-1633339886000

- playwright/_impl/_transport.py
Fixes https://github.com/microsoft/playwright-python/issues/1001
cc @kumaraditya303
> chore: allow custom PLAYWRIGHT_BROWSERS_PATH with Pyinstaller

- tests/async/test_browsercontext.py
- tests/async/test_defaultbrowsercontext.py
- tests/async/test_popup.py
- tests/server.py
> test: have server.set_auth accepting strings

- README.md
- playwright/_impl/_api_structures.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_fetch.py
- playwright/_impl/_frame.py
- playwright/_impl/_helper.py
- playwright/_impl/_locator.py
- playwright/_impl/_network.py
- playwright/_impl/_object_factory.py
- playwright/_impl/_page.py
- playwright/_impl/_playwright.py
- playwright/_impl/_tracing.py
- playwright/async_api/__init__.py
- playwright/async_api/_generated.py
- playwright/sync_api/__init__.py
- playwright/sync_api/_context_manager.py
- playwright/sync_api/_generated.py
- pyproject.toml
- scripts/documentation_provider.py
- scripts/generate_api.py
- setup.py
- tests/async/test_fetch_browser_context.py
- tests/async/test_fetch_global.py
- tests/async/test_frames.py
- tests/async/test_locators.py
- tests/server.py
- tests/sync/test_fetch_browser_context.py
- tests/sync/test_fetch_global.py
- tests/sync/test_locators.py
https://github.com/microsoft/playwright-python/issues/1004
> feat(roll): roll Playwright 1.17.0-next-1636463074000

- playwright/_impl/_locator.py
- tests/sync/test_locators.py
Closes https://github.com/microsoft/playwright-python/issues/1005
> chore:  frame locator repr

- playwright/_impl/_api_structures.py
- playwright/_impl/_assertions.py
- playwright/_impl/_locator.py
- playwright/_impl/_page.py
- playwright/_impl/_path_utils.py
- playwright/async_api/__init__.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/expected_api_mismatch.txt
- scripts/generate_api.py
- scripts/generate_async_api.py
- scripts/generate_sync_api.py
- setup.py
- tests/async/test_assertions.py
> feat: added web-first assertions

- setup.py
Cherry pick: 37c0533e04e34a6f8cd8feb7bacac99cd585b9d7
> cherry-pick(release-1.17): fix: setup.py --all only put local driver if arch matches

- playwright/_impl/_browser.py
- playwright/_impl/_browser_type.py
We do it when we establish the connection.
> chore: remove sdkLanguage in newContext/connectOverCDP

- README.md
- playwright/_impl/_assertions.py
- playwright/async_api/_generated.py
- playwright/sync_api/__init__.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_accessibility.py
- tests/sync/test_accessibility.py
- tests/sync/test_assertions.py
Depends on https://github.com/microsoft/playwright/pull/10465
Added missing sync assertions #988
> chore: add sync assertions

- playwright/__main__.py
> fix: show PY version instead of driver version

- pyproject.toml
> test: fix pytest asyncio deprecation warnings

- playwright/__main__.py
- playwright/_impl/_driver.py
- playwright/_impl/_transport.py
- tests/async/test_fetch_global.py
> chore: provide driver with the host-lang version

- meta.yaml
- setup.py
> chore: pin dependencies

- meta.yaml
- setup.py
> cherry-pick(release-1.18): chore: pin dependencies

- playwright/_impl/_sync_base.py
this fixes the following test:
```
================================== FAILURES ===================================
______________________ test_expect_file_chooser[firefox] ______________________
page = <Page url='about:blank'>
def test_expect_file_chooser(page: Page) -> None:
page.set_content("<input type=file></input>")
with page.expect_file_chooser() as fc_info:
page.click('input[type="file"]')
fc = fc_info.value
>       fc.set_files(
{"name": "test.txt", "mimeType": "text/plain", "buffer": b"Hello World"}
)
E       AttributeError: 'NoneType' object has no attribute 'set_files'
tests\sync\test_input.py:24: AttributeError
```
> chore: unflake test_expect_file_chooser tests

- README.md
- playwright/_impl/_browser_type.py
- playwright/_impl/_element_handle.py
- playwright/_impl/_locator.py
- playwright/_impl/_page.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_browsercontext_add_cookies.py
- tests/async/test_browsercontext_cookies.py
- tests/async/test_defaultbrowsercontext.py
- tests/async/test_headful.py
- tests/async/test_interception.py
- tests/async/test_network.py
- tests/async/test_resource_timing.py
- tests/sync/test_resource_timing.py
> chore: roll Playwright to 1.20

- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/documentation_provider.py
Fixes https://github.com/microsoft/playwright-python/issues/1031
Depends on https://github.com/microsoft/playwright-python/pull/1240 for the new driver, but this shows the new links quite nicely.
> chore: fix broken links in generated code

- playwright/_impl/_fetch.py
- tests/async/test_request_fulfill.py
- tests/async/test_request_intercept.py
- tests/sync/test_request_fulfill.py
- tests/sync/test_request_intercept.py
Fixes https://github.com/microsoft/playwright-python/issues/1312
> fix: request interception

- tests/async/test_defaultbrowsercontext.py
Ports:
- [tests: nuke the failing/flaky test playwright](https://github.com/microsoft/playwright/pull/14724#event-6774053878)
> chore: remove failing/flaky test

- playwright/_impl/_browser.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_helper.py
- playwright/_impl/_local_utils.py
- playwright/_impl/_page.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_har.py
- tests/sync/test_har.py
> chore: port update option for routeFromHar

- utils/docker/Dockerfile.bionic
- utils/docker/Dockerfile.focal
https://github.com/microsoft/playwright-dotnet/issues/2223
> chore: add 'gpg' package to Docker images

- playwright/_impl/_video.py
- tests/async/test_video.py
- tests/sync/test_video.py
Resolves #1462.
Docs: https://github.com/microsoft/playwright/pull/16120
> chore: prevent save_as from hanging in sync mode

- local-requirements.txt
- pyproject.toml
Relates https://github.com/microsoft/playwright-python/issues/1500.
> fix: pin setuptools in build-system

- utils/docker/publish_docker.sh
Fixes https://github.com/microsoft/playwright-python/issues/1518
> devops: fix Docker jammy publishing

- utils/docker/publish_docker.sh
SHA: 5066b706dd985e957a0444921f84aaab9a660b4d
> cherry-pick(#1519): devops: fix Docker jammy publishing

- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/documentation_provider.py
- scripts/expected_api_mismatch.txt
- scripts/generate_api.py
- scripts/generate_async_api.py
- scripts/generate_sync_api.py
> Use None instead of NoneType for API type annotations

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .github/workflows/publish_canary_docker.yml
- .github/workflows/publish_release_docker.yml
- .github/workflows/test_docker.yml
> devops: upgrade GitHub Actions

- playwright/_impl/_transport.py
Fixes https://github.com/microsoft/playwright-python/issues/1711
Relates https://github.com/microsoft/playwright-python/pull/1648
> chore: do not set no_window to the process

- playwright/_impl/_page.py
Fixes https://github.com/microsoft/playwright-python/issues/1748
> chore: fix page.pause()

- .pre-commit-config.yaml
- playwright/_impl/_browser.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/async_api/_generated.py
- playwright/sync_api/_context_manager.py
- playwright/sync_api/_generated.py
- scripts/generate_api.py
- tests/async/test_har.py
- tests/sync/test_har.py
https://github.com/PyCQA/isort/issues/2077
> chore: update pre-commit

- .gitignore
- playwright/_impl/_assertions.py
- playwright/async_api/__init__.py
- playwright/sync_api/__init__.py
- tests/async/test_assertions.py
- tests/sync/test_assertions.py
RP add support custom message to expect expressions and resolve #1310 issue
> feat: add support for custom expect message

- README.md
- playwright/_impl/_browser_context.py
- playwright/_impl/_connection.py
- playwright/_impl/_local_utils.py
- playwright/_impl/_locator.py
- playwright/_impl/_page.py
- playwright/_impl/_tracing.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/expected_api_mismatch.txt
- setup.py
- tests/async/test_element_handle.py
- tests/async/test_har.py
- tests/async/test_locators.py
- tests/async/test_navigation.py
- tests/async/test_tracing.py
- tests/sync/test_element_handle.py
- tests/sync/test_har.py
- tests/sync/test_locators.py
- tests/sync/test_tracing.py
https://github.com/microsoft/playwright-python/issues/1777
> chore: roll Playwright to 1.32.0-alpha-mar-15-2023

- playwright/_impl/_locator.py
- tests/async/test_selectors_get_by.py
Fixes https://github.com/microsoft/playwright-python/issues/1813
> fix: get_by_role include_hidden options

- tests/async/test_fetch_global.py
- tests/server.py
- tests/sync/test_fetch_global.py
https://github.com/microsoft/playwright-dotnet/issues/2509
> test: fetch with None in json payload

- playwright/_impl/_local_utils.py
- tests/async/test_tracing.py
Fixes https://github.com/microsoft/playwright-python/issues/1835
> fix: discard trace without path

- README.md
- playwright/_impl/_api_structures.py
- playwright/_impl/_assertions.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_frame.py
- playwright/_impl/_locator.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/documentation_provider.py
- setup.py
- tests/async/test_assertions.py
- tests/async/test_browsercontext.py
- tests/async/test_fetch_global.py
- tests/async/test_locators.py
- tests/async/test_navigation.py
- tests/sync/test_assertions.py
- tests/sync/test_fetch_global.py
- tests/sync/test_locators.py
Fixes https://github.com/microsoft/playwright-python/issues/1777
> chore(roll): roll Playwright to 1.33.0-alpha-apr-12-2023

- README.md
- playwright/_impl/_network.py
- playwright/_impl/_stream.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_click.py
- tests/async/test_navigation.py
- tests/async/test_page_request_intercept.py
- tests/async/test_worker.py
- tests/sync/test_page_request_intercept.py
Fixes https://github.com/microsoft/playwright-python/issues/1865
> chore(roll): roll Playwright to 1.33.0-beta-1682447195000

- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/documentation_provider.py
Fixes https://github.com/microsoft/playwright-python/issues/1911
> chore: render deprecated method parameters

- playwright/_impl/_assertions.py
- playwright/async_api/__init__.py
- playwright/sync_api/__init__.py
- tests/async/test_assertions.py
- tests/sync/test_assertions.py
https://github.com/microsoft/playwright-python/issues/1358
> chore: add ability to set expect timeout

- README.md
- playwright/_impl/_browser_context.py
- playwright/_impl/_element_handle.py
- playwright/_impl/_helper.py
- playwright/_impl/_locator.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/_impl/_set_input_files_helpers.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/assets/input/fileupload-multi.html
- tests/async/test_input.py
Fixes https://github.com/microsoft/playwright-python/issues/1945
> chore(roll): roll Playwright to 1.35.0-beta-1686247644000

- README.md
- playwright/_impl/_api_types.py
- playwright/_impl/_browser.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_connection.py
- playwright/_impl/_frame.py
- playwright/_impl/_helper.py
- playwright/_impl/_locator.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/_impl/_page_error.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/documentation_provider.py
- scripts/expected_api_mismatch.txt
- scripts/generate_api.py
- scripts/generate_async_api.py
- scripts/generate_sync_api.py
- setup.py
- tests/async/test_browsercontext_events.py
- tests/async/test_locators.py
- tests/async/test_network.py
- tests/async/test_page_network_request.py
- tests/async/test_page_request_intercept.py
- tests/async/test_popup.py
- tests/async/test_request_fulfill.py
- tests/sync/test_request_fulfill.py
Fixes https://github.com/microsoft/playwright-python/issues/2048
> feat(roll): roll to Playwright 1.38.0-alpha-sep-4-2023

- .azure-pipelines/publish.yml
- .github/workflows/publish.yml
- setup.py
Fixes https://github.com/microsoft/playwright-python/issues/2045
> devops: Set up CI/CD with Azure Pipelines

- .github/workflows/ci.yml
- meta.yaml
- setup.py
https://github.com/microsoft/playwright-python/issues/2096
> chore: update greenlet to 3.0.0

- playwright/_impl/_api_structures.py
- scripts/generate_api.py
- tests/async/test_browsercontext_add_cookies.py
- tests/async/test_launcher.py
- tests/sync/test_assertions.py
- tests/sync/test_browsercontext_request_fallback.py
- tests/sync/test_fetch_browser_context.py
https://github.com/microsoft/playwright-python/issues/2174
> test: unskip tests / unignore linting in tests

- playwright/_impl/_assertions.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_browser_type.py
- playwright/_impl/_frame.py
- playwright/_impl/_locator.py
- playwright/_impl/_page.py
- playwright/_impl/_selectors.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/generate_api.py
Follow-up on https://github.com/microsoft/playwright-python/pull/2205 to prevent it in the future.
> chore: enforce no underscores in impl class params

- playwright/_impl/_glob.py
- playwright/_impl/_helper.py
- tests/async/test_browsercontext_request_fallback.py
- tests/async/test_interception.py
- tests/async/test_page_request_fallback.py
- tests/sync/test_browsercontext_request_fallback.py
- tests/sync/test_page_request_fallback.py
Fixes https://github.com/microsoft/playwright-python/issues/2193
> chore: migrate to own glob parser

- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/documentation_provider.py
https://github.com/microsoft/playwright-python/issues/2256
> fix: only render sync/async code blocks in generated classes

- README.md
> docs(readme.md): update broken link

- meta.yaml
- playwright/_impl/_api_structures.py
- playwright/_impl/_browser_context.py
- playwright/_impl/_connection.py
- playwright/_impl/_element_handle.py
- playwright/_impl/_frame.py
- playwright/_impl/_helper.py
- playwright/_impl/_locator.py
- playwright/_impl/_network.py
- playwright/_impl/_page.py
- playwright/_impl/_set_input_files_helpers.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- scripts/generate_api.py
- setup.py
Resolves [#2301](https://github.com/microsoft/playwright-python/issues/2301).
> chore: remove unnecessary 'type-extensions' requirement

- README.md
- playwright/_impl/_connection.py
- playwright/_impl/_frame.py
- playwright/_impl/_greenlets.py
- playwright/_impl/_har_router.py
- playwright/_impl/_helper.py
- playwright/_impl/_js_handle.py
- playwright/_impl/_page.py
- playwright/async_api/_generated.py
- playwright/sync_api/_context_manager.py
- playwright/sync_api/_generated.py
- setup.py
- tests/assets/headings.html
- tests/assets/input/handle-locator.html
- tests/async/test_browsercontext_storage_state.py
- tests/async/test_click.py
- tests/async/test_element_handle.py
- tests/async/test_har.py
- tests/async/test_page_add_locator_handler.py
- tests/async/test_pdf.py
- tests/conftest.py
- tests/sync/conftest.py
- tests/sync/test_element_handle.py
- tests/sync/test_page_add_locator_handler.py
Fixes https://github.com/microsoft/playwright-python/issues/2246
Fixes https://github.com/microsoft/playwright-python/pull/2261
> chore(roll): roll Playwright to 1.42.0-alpha-2024-02-19

- playwright/_impl/_connection.py
Resolves [issue](https://github.com/microsoft/playwright-python/issues/2305)
> fix: bug initializing `sync_playwright` when using uvloop.EventPolicy.

- README.md
- playwright/_impl/_browser_context.py
- playwright/_impl/_js_handle.py
- playwright/_impl/_locator.py
- playwright/_impl/_network.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_browsercontext_clearcookies.py
- tests/async/test_browsercontext_storage_state.py
- tests/async/test_element_handle.py
- tests/async/test_locators.py
- tests/async/test_page_network_request.py
- tests/sync/test_browsercontext_storage_state.py
- tests/sync/test_element_handle.py
- tests/sync/test_locators.py
Fixes https://github.com/microsoft/playwright-python/issues/2328
> feat(roll): roll Playwright to 1.43.0-beta-1711484700000

- meta.yaml
Align it with the `setup.py` file: https://github.com/microsoft/playwright-python/blob/d12ce3bce59b01b6db5f722c936edb9f7d56fff1/setup.py#L220-L223
> fix(conda): update pyee version

- tests/async/test_click.py
> test: unflake Firefox tests

- playwright/_impl/_fetch.py
- tests/async/test_fetch_global.py
Fixes https://github.com/microsoft/playwright-python/issues/2475
> fix(fetch): serialise empty array in 'data' as JSON

- playwright/_impl/_transport.py
the globals get should be getting a double underscore value, not single
> fix from single underscore to double underscore

- playwright/_impl/_transport.py
Fix for https://github.com/microsoft/playwright-python/issues/2633
> Use `Process.communicate` instead of `Process.wait`

- README.md
- playwright/_impl/_assertions.py
- playwright/_impl/_network.py
- playwright/async_api/_generated.py
- playwright/sync_api/_generated.py
- setup.py
- tests/async/test_assertions.py
- tests/async/test_locators.py
- tests/async/test_tracing.py
- tests/sync/test_assertions.py
- tests/sync/test_locators.py
- tests/sync/test_tracing.py
Fixes https://github.com/microsoft/playwright-python/issues/2653
> chore(roll): roll Playwright to v1.50

- playwright/_impl/_locator.py
- tests/async/test_fill.py
- tests/async/test_locators.py
- tests/sync/test_locators.py
Fixes https://github.com/microsoft/playwright-python/issues/2731
> fix(locator): fix is_enabled method

- .azure-pipelines/publish.yml
Similar to https://github.com/microsoft/playwright-browsers/pull/1524.
> devops: use ESRP PME for publishing

- meta.yaml
- pyproject.toml
- requirements.txt
New [major release for pyee](https://github.com/jfhbrook/pyee/releases/tag/v13.0.0)
> build(deps): bump pyee from 12.x to 13.x

- tests/async/test_defaultbrowsercontext.py
Fixes https://github.com/microsoft/playwright-python/actions/runs/14928205039/job/41937782691#step:8:1539
> test: unflake test_context_cookies_should_work test in Edge

- tests/async/test_chromium_tracing.py
Similar as https://github.com/microsoft/playwright/pull/36873/files#diff-7a96ca2a6cb1682613cc5aaa00bc6e25b276609eac2e1d4512f5bb1722ab066b
> test: unflake cr tracing test

- scripts/documentation_provider.py
- scripts/generate_api.py
Fixes https://github.com/microsoft/playwright-python/issues/2959
Discovered it while @agg23 was rolling Python recently.
Looks like related to https://github.com/python/cpython/issues/133789
> chore: fix api generation under Python 3.13
